export const SENTENCE_DB = [
  {
    id: 1,
    displaySentence: "The quick brown fox jumps over the lazy ___.",
    fullSentence: "The quick brown fox jumps over the lazy dog.",
    answer: "dog",
    options: ["cat", "dog", "mouse", "cow"],
    translation: "Con cáo nâu nhanh nhẹn nhảy qua con chó lười biếng.",
    ipa: "/ðə kwɪk braʊn fɒks dʒʌmps ˈəʊvə ðə ˈleɪzi dɒg/",
    hint: "Man's best friend. 🐶",
  },
  {
    id: 2,
    displaySentence: "I would like a cup of ___ with milk, please.",
    fullSentence: "I would like a cup of coffee with milk, please.",
    answer: "coffee",
    options: ["tea", "water", "coffee", "juice"],
    translation: "Làm ơn cho tôi một tách cà phê với sữa.",
    ipa: "/aɪ wʊd laɪk ə kʌp əv ˈkɒfi wɪð mɪlk, pliːz/",
    hint: "A popular caffeinated morning drink. ☕",
  },
  {
    id: 3,
    displaySentence: "She is wearing a beautiful red ___ to the party.",
    fullSentence: "She is wearing a beautiful red dress to the party.",
    answer: "dress",
    options: ["shirt", "pants", "hat", "dress"],
    translation: "Cô ấy đang mặc một chiếc váy đỏ tuyệt đẹp đến bữa tiệc.",
    ipa: "/ʃi ɪz ˈweərɪŋ ə ˈbjuːtɪfʊl rɛd drɛs tuː ðə ˈpɑːti/",
    hint: "A one-piece garment for women. 👗",
  },
  {
    id: 4,
    displaySentence: "Could you tell me the ___ to the nearest train station?",
    fullSentence: "Could you tell me the way to the nearest train station?",
    answer: "way",
    options: ["way", "time", "price", "reason"],
    translation: "Bạn có thể chỉ cho tôi đường đến ga tàu gần nhất không?",
    ipa: "/kʊd juː tɛl miː ðə weɪ tuː ðə ˈnɪərɪst treɪn ˈsteɪʃən/",
    hint: "Direction or path. 🗺️",
  },
  {
    id: 5,
    displaySentence: "He plays the ___ very well in the school band.",
    fullSentence: "He plays the guitar very well in the school band.",
    answer: "guitar",
    options: ["guitar", "football", "computer", "kitchen"],
    translation: "Anh ấy chơi guitar rất giỏi trong ban nhạc của trường.",
    ipa: "/hi pleɪz ðə gɪˈtɑː ˈvɛri wɛl ɪn ðə skuːl bænd/",
    hint: "A stringed musical instrument. 🎸",
  },
  {
    id: 6,
    displaySentence:
      "We need to buy some fresh ___ and vegetables for the salad.",
    fullSentence:
      "We need to buy some fresh fruits and vegetables for the salad.",
    answer: "fruits",
    options: ["fruits", "meat", "bread", "candy"],
    translation:
      "Chúng ta cần mua một ít trái cây và rau quả tươi cho món salad.",
    ipa: "/wi niːd tuː baɪ sʌm frɛʃ fruːts ænd ˈvɛʤɪtəb(ə)lz fɔː ðə ˈsæləd/",
    hint: "Apples, bananas, oranges... 🍎",
  },
  {
    id: 7,
    displaySentence: "The ___ is shining brightly in the clear blue sky.",
    fullSentence: "The sun is shining brightly in the clear blue sky.",
    answer: "sun",
    options: ["moon", "star", "sun", "cloud"],
    translation: "Mặt trời đang chiếu sáng rực rỡ trên bầu trời xanh trong.",
    ipa: "/ðə sʌn ɪz ˈʃaɪnɪŋ ˈbraɪtli ɪn ðə klɪə bluː skaɪ/",
    hint: "The star around which the earth orbits. ☀️",
  },
  {
    id: 8,
    displaySentence:
      "Please remember to lock the ___ before you leave the house.",
    fullSentence:
      "Please remember to lock the door before you leave the house.",
    answer: "door",
    options: ["window", "door", "car", "safe"],
    translation: "Vui lòng nhớ khóa cửa trước khi bạn rời khỏi nhà.",
    ipa: "/pliːz rɪˈmɛmbə tuː lɒk ðə dɔː bɪˈfɔː juː liːv ðə haʊs/",
    hint: "The main entrance to a room or building. 🚪",
  },
  {
    id: 9,
    displaySentence: "I enjoy reading a good ___ before going to sleep.",
    fullSentence: "I enjoy reading a good book before going to sleep.",
    answer: "book",
    options: ["movie", "book", "song", "game"],
    translation: "Tôi thích đọc một cuốn sách hay trước khi đi ngủ.",
    ipa: "/aɪ ɪnˈʤɔɪ ˈriːdɪŋ ə gʊd bʊk bɪˈfɔː ˈgəʊɪŋ tuː sliːp/",
    hint: "Contains pages with text. 📖",
  },
  {
    id: 10,
    displaySentence: "They are traveling to Paris by ___ tomorrow morning.",
    fullSentence: "They are traveling to Paris by plane tomorrow morning.",
    answer: "plane",
    options: ["bus", "train", "plane", "bicycle"],
    translation: "Họ sẽ đi du lịch đến Paris bằng máy bay vào sáng ngày mai.",
    ipa: "/ðeɪ ɑː ˈtrævlɪŋ tuː ˈpærɪs baɪ pleɪn təˈmɒrəʊ ˈmɔːnɪŋ/",
    hint: "It flies in the sky. ✈️",
  },
  {
    id: 11,
    displaySentence: "My mother is cooking dinner in the ___.",
    fullSentence: "My mother is cooking dinner in the kitchen.",
    answer: "kitchen",
    options: ["bedroom", "kitchen", "garden", "garage"],
    translation: "Mẹ tôi đang nấu bữa tối trong nhà bếp.",
    ipa: "/maɪ ˈmʌðə ɪz ˈkʊkɪŋ ˈdɪnə ɪn ðə ˈkɪtʃɪn/",
    hint: "A room where you prepare and cook food. 🍳",
  },
  {
    id: 12,
    displaySentence: "There are many beautiful flowers in the ___.",
    fullSentence: "There are many beautiful flowers in the garden.",
    answer: "garden",
    options: ["garden", "kitchen", "office", "library"],
    translation: "Có rất nhiều bông hoa đẹp trong khu vườn.",
    ipa: "/ðeər ɑː ˈmɛni ˈbjuːtɪfʊl ˈflaʊəz ɪn ðə ˈgɑːdn/",
    hint: "A place where plants and flowers grow. 🌸",
  },
  {
    id: 13,
    displaySentence: "Please turn off the ___ before you go to bed.",
    fullSentence: "Please turn off the light before you go to bed.",
    answer: "light",
    options: ["door", "light", "table", "pillow"],
    translation: "Vui lòng tắt đèn trước khi bạn đi ngủ.",
    ipa: "/pliːz tɜːn ɒf ðə laɪt bɪˈfɔː juː gəʊ tuː bɛd/",
    hint: "It helps you see in the dark. 💡",
  },
  {
    id: 14,
    displaySentence: "I usually drink a glass of ___ after exercising.",
    fullSentence: "I usually drink a glass of water after exercising.",
    answer: "water",
    options: ["coffee", "juice", "water", "milk"],
    translation: "Tôi thường uống một cốc nước sau khi tập thể dục.",
    ipa: "/aɪ ˈjuːʒuəli drɪŋk ə glɑːs əv ˈwɔːtə ˈɑːftə ˈɛksəsaɪzɪŋ/",
    hint: "You need it to stay hydrated. 💧",
  },
  {
    id: 15,
    displaySentence: "My brother goes to school by ___ every morning.",
    fullSentence: "My brother goes to school by bicycle every morning.",
    answer: "bicycle",
    options: ["bicycle", "plane", "ship", "taxi"],
    translation: "Anh trai tôi đi học bằng xe đạp mỗi sáng.",
    ipa: "/maɪ ˈbrʌðə gəʊz tuː skuːl baɪ ˈbaɪsɪkəl ˈɛvri ˈmɔːnɪŋ/",
    hint: "A two-wheeled vehicle you pedal. 🚲",
  },
  {
    id: 16,
    displaySentence: "She bought a new pair of ___ for the summer.",
    fullSentence: "She bought a new pair of shoes for the summer.",
    answer: "shoes",
    options: ["gloves", "shoes", "socks", "shirts"],
    translation: "Cô ấy đã mua một đôi giày mới cho mùa hè.",
    ipa: "/ʃiː bɔːt ə njuː peər əv ʃuːz fɔː ðə ˈsʌmə/",
    hint: "You wear them on your feet. 👟",
  },
  {
    id: 17,
    displaySentence: "The children are playing football in the ___.",
    fullSentence: "The children are playing football in the park.",
    answer: "park",
    options: ["park", "kitchen", "hospital", "museum"],
    translation: "Những đứa trẻ đang chơi bóng đá trong công viên.",
    ipa: "/ðə ˈtʃɪldrən ɑː ˈpleɪɪŋ ˈfʊtbɔːl ɪn ðə pɑːk/",
    hint: "A public green space for people to relax. 🌳",
  },
  {
    id: 18,
    displaySentence: "I use my ___ to call my friends every day.",
    fullSentence: "I use my phone to call my friends every day.",
    answer: "phone",
    options: ["phone", "camera", "radio", "television"],
    translation: "Tôi sử dụng điện thoại để gọi cho bạn bè mỗi ngày.",
    ipa: "/aɪ juːz maɪ fəʊn tuː kɔːl maɪ frɛndz ˈɛvri deɪ/",
    hint: "You use it to make calls and send messages. 📱",
  },
  {
    id: 19,
    displaySentence: "We can see many animals at the ___.",
    fullSentence: "We can see many animals at the zoo.",
    answer: "zoo",
    options: ["zoo", "bank", "school", "station"],
    translation: "Chúng ta có thể nhìn thấy nhiều loài động vật ở sở thú.",
    ipa: "/wiː kən siː ˈmɛni ˈænɪməlz æt ðə zuː/",
    hint: "A place where many animals are kept for people to see. 🦁",
  },
  {
    id: 20,
    displaySentence: "He puts his books on the ___ next to his bed.",
    fullSentence: "He puts his books on the table next to his bed.",
    answer: "table",
    options: ["table", "window", "carpet", "ceiling"],
    translation: "Anh ấy đặt sách lên chiếc bàn cạnh giường.",
    ipa: "/hi pʊts hɪz bʊks ɒn ðə ˈteɪbəl nɛkst tuː hɪz bɛd/",
    hint: "You can put books and other things on it. 🪑",
  },
  {
    id: 21,
    displaySentence: "My father reads the ___ every morning.",
    fullSentence: "My father reads the newspaper every morning.",
    answer: "newspaper",
    options: ["newspaper", "magazine", "dictionary", "notebook"],
    translation: "Bố tôi đọc báo mỗi sáng.",
    ipa: "/maɪ ˈfɑːðə riːdz ðə ˈnjuːzˌpeɪpə ˈɛvri ˈmɔːnɪŋ/",
    hint: "It contains daily news and reports. 📰",
  },
  {
    id: 22,
    displaySentence: "The students are studying in the ___.",
    fullSentence: "The students are studying in the library.",
    answer: "library",
    options: ["library", "stadium", "restaurant", "market"],
    translation: "Các học sinh đang học trong thư viện.",
    ipa: "/ðə ˈstjuːdənts ɑː ˈstʌdiɪŋ ɪn ðə ˈlaɪbrəri/",
    hint: "A quiet place with many books. 📚",
  },
  {
    id: 23,
    displaySentence: "We need an umbrella because it is ___.",
    fullSentence: "We need an umbrella because it is raining.",
    answer: "raining",
    options: ["raining", "snowing", "shining", "blowing"],
    translation: "Chúng ta cần một chiếc ô vì trời đang mưa.",
    ipa: "/wi niːd ən ʌmˈbrɛlə bɪˈkɒz ɪt ɪz ˈreɪnɪŋ/",
    hint: "Water is falling from the sky. ☔",
  },
  {
    id: 24,
    displaySentence: "She is very ___ because she passed the exam.",
    fullSentence: "She is very happy because she passed the exam.",
    answer: "happy",
    options: ["angry", "tired", "happy", "worried"],
    translation: "Cô ấy rất vui vì đã vượt qua kỳ thi.",
    ipa: "/ʃiː ɪz ˈvɛri ˈhæpi bɪˈkɒz ʃiː pɑːst ði ɪgˈzæm/",
    hint: "Feeling good and pleased. 😊",
  },
  {
    id: 25,
    displaySentence: "Please put the dirty clothes in the ___.",
    fullSentence: "Please put the dirty clothes in the basket.",
    answer: "basket",
    options: ["basket", "drawer", "shelf", "closet"],
    translation: "Vui lòng cho quần áo bẩn vào giỏ.",
    ipa: "/pliːz pʊt ðə ˈdɜːti kləʊðz ɪn ðə ˈbɑːskɪt/",
    hint: "A container used for carrying or holding things. 🧺",
  },
  {
    id: 26,
    displaySentence: "I always brush my ___ before going to bed.",
    fullSentence: "I always brush my teeth before going to bed.",
    answer: "teeth",
    options: ["hands", "hair", "teeth", "ears"],
    translation: "Tôi luôn đánh răng trước khi đi ngủ.",
    ipa: "/aɪ ˈɔːlweɪz brʌʃ maɪ tiːθ bɪˈfɔː ˈgəʊɪŋ tuː bɛd/",
    hint: "You brush them with a toothbrush. 🪥",
  },
  {
    id: 27,
    displaySentence: "The doctor works at the ___ near my house.",
    fullSentence: "The doctor works at the hospital near my house.",
    answer: "hospital",
    options: ["hospital", "library", "factory", "theater"],
    translation: "Bác sĩ làm việc tại bệnh viện gần nhà tôi.",
    ipa: "/ðə ˈdɒktə wɜːks æt ðə ˈhɒspɪtəl nɪə maɪ haʊs/",
    hint: "A place where sick people receive medical care. 🏥",
  },
  {
    id: 28,
    displaySentence: "They are watching an exciting ___ on television.",
    fullSentence: "They are watching an exciting movie on television.",
    answer: "movie",
    options: ["movie", "book", "song", "letter"],
    translation: "Họ đang xem một bộ phim thú vị trên truyền hình.",
    ipa: "/ðeɪ ɑː ˈwɒtʃɪŋ ən ɪkˈsaɪtɪŋ ˈmuːvi ɒn ˈtɛlɪvɪʒən/",
    hint: "A story you watch on a screen. 🎬",
  },
  {
    id: 29,
    displaySentence: "The teacher writes on the ___ during the lesson.",
    fullSentence: "The teacher writes on the board during the lesson.",
    answer: "board",
    options: ["board", "floor", "door", "wall"],
    translation: "Giáo viên viết lên bảng trong giờ học.",
    ipa: "/ðə ˈtiːtʃə raɪts ɒn ðə bɔːd ˈdjʊərɪŋ ðə ˈlɛsn/",
    hint: "Students look at it during a class. 🧑‍🏫",
  },
  {
    id: 30,
    displaySentence: "We usually have lunch at ___ twelve o'clock.",
    fullSentence: "We usually have lunch at about twelve o'clock.",
    answer: "about",
    options: ["about", "under", "between", "through"],
    translation: "Chúng tôi thường ăn trưa vào khoảng mười hai giờ.",
    ipa: "/wiː ˈjuːʒuəli hæv lʌntʃ æt əˈbaʊt twɛlv əˈklɒk/",
    hint: "It means approximately or around. ⏰",
  },
  {
    id: 31,
    displaySentence: "I have a pet ___ that loves to catch mice.",
    fullSentence: "I have a pet cat that loves to catch mice.",
    answer: "cat",
    options: ["dog", "cat", "bird", "fish"],
    translation: "Tôi có một chú mèo cưng rất thích bắt chuột.",
    ipa: "/aɪ hæv ə pɛt kæt ðæt lʌvz tuː kætʃ maɪs/",
    hint: "It says meow. 🐱",
  },
  {
    id: 32,
    displaySentence: "The ___ gave us a lot of homework today.",
    fullSentence: "The teacher gave us a lot of homework today.",
    answer: "teacher",
    options: ["doctor", "farmer", "teacher", "singer"],
    translation:
      "Giáo viên đã giao cho chúng tôi rất nhiều bài tập về nhà hôm nay.",
    ipa: "/ðə ˈtiːtʃə ɡeɪv ʌs ə lɒt əv ˈhəʊmwɜːk təˈdeɪ/",
    hint: "A person who helps you learn. 👩‍🏫",
  },
  {
    id: 33,
    displaySentence: "I use my ___ to send emails and browse the web.",
    fullSentence: "I use my computer to send emails and browse the web.",
    answer: "computer",
    options: ["television", "computer", "radio", "microwave"],
    translation: "Tôi sử dụng máy tính để gửi email và lướt web.",
    ipa: "/aɪ juːz maɪ kəmˈpjuːtə tuː sɛnd ˈiːmeɪlz ænd braʊz ðə wɛb/",
    hint: "An electronic device for processing data. 💻",
  },
  {
    id: 34,
    displaySentence: "She loves listening to pop ___ on her way to work.",
    fullSentence: "She loves listening to pop music on her way to work.",
    answer: "music",
    options: ["music", "news", "noise", "movies"],
    translation: "Cô ấy thích nghe nhạc pop trên đường đi làm.",
    ipa: "/ʃiː lʌvz ˈlɪsnɪŋ tuː pɒp ˈmjuːzɪk ɒn hɜː weɪ tuː wɜːk/",
    hint: "Melodies and sounds you listen to. 🎵",
  },
  {
    id: 35,
    displaySentence: "There is a large apple ___ in our backyard.",
    fullSentence: "There is a large apple tree in our backyard.",
    answer: "tree",
    options: ["flower", "tree", "grass", "rock"],
    translation: "Có một cây táo lớn ở sân sau nhà chúng tôi.",
    ipa: "/ðeər ɪz ə lɑːdʒ ˈæpl triː ɪn ˈaʊə ˌbækˈjɑːd/",
    hint: "A tall plant with a trunk and branches. 🌳",
  },
  {
    id: 36,
    displaySentence: "I put my laptop and books in my ___.",
    fullSentence: "I put my laptop and books in my bag.",
    answer: "bag",
    options: ["bag", "pocket", "shoe", "hat"],
    translation: "Tôi để máy tính xách tay và sách vào túi của mình.",
    ipa: "/aɪ pʊt maɪ ˈlæptɒp ænd bʊks ɪn maɪ bæɡ/",
    hint: "You use it to carry things. 🎒",
  },
  {
    id: 37,
    displaySentence: "Can I borrow a blue ___ to write my name?",
    fullSentence: "Can I borrow a blue pen to write my name?",
    answer: "pen",
    options: ["eraser", "ruler", "pen", "desk"],
    translation: "Tôi có thể mượn một cây bút xanh để viết tên không?",
    ipa: "/kæn aɪ ˈbɒrəʊ ə bluː pɛn tuː raɪt maɪ neɪm/",
    hint: "A tool used for writing with ink. 🖊️",
  },
  {
    id: 38,
    displaySentence: "I lost my house ___ and cannot get inside.",
    fullSentence: "I lost my house key and cannot get inside.",
    answer: "key",
    options: ["card", "key", "wallet", "phone"],
    translation: "Tôi làm mất chìa khóa nhà và không thể vào trong.",
    ipa: "/aɪ lɒst maɪ haʊs kiː ænd ˈkænɒt ɡɛt ɪnˈsaɪd/",
    hint: "Used to open locks and doors. 🔑",
  },
  {
    id: 39,
    displaySentence: "You need ___ to buy food and clothes.",
    fullSentence: "You need money to buy food and clothes.",
    answer: "money",
    options: ["time", "money", "water", "paper"],
    translation: "Bạn cần tiền để mua thức ăn và quần áo.",
    ipa: "/juː niːd ˈmʌni tuː baɪ fuːd ænd kləʊðz/",
    hint: "Coins and banknotes. 💵",
  },
  {
    id: 40,
    displaySentence: "He is my best ___, we do everything together.",
    fullSentence: "He is my best friend, we do everything together.",
    answer: "friend",
    options: ["enemy", "stranger", "boss", "friend"],
    translation:
      "Anh ấy là người bạn thân nhất của tôi, chúng tôi làm mọi thứ cùng nhau.",
    ipa: "/hiː ɪz maɪ bɛst frɛnd, wiː duː ˈɛvrɪθɪŋ təˈɡɛðə/",
    hint: "A person you like and know well. 🤝",
  },
  {
    id: 41,
    displaySentence: "The ___ on the wall shows that it is 5 PM.",
    fullSentence: "The clock on the wall shows that it is 5 PM.",
    answer: "clock",
    options: ["clock", "picture", "mirror", "calendar"],
    translation: "Đồng hồ trên tường chỉ 5 giờ chiều.",
    ipa: "/ðə klɒk ɒn ðə wɔːl ʃəʊz ðæt ɪt ɪz faɪv piː-ɛm/",
    hint: "Tells you the time. 🕒",
  },
  {
    id: 42,
    displaySentence: "Smile! I want to take a picture with my new ___.",
    fullSentence: "Smile! I want to take a picture with my new camera.",
    answer: "camera",
    options: ["phone", "camera", "radio", "watch"],
    translation:
      "Cười lên nào! Tôi muốn chụp một bức ảnh bằng chiếc máy ảnh mới.",
    ipa: "/smaɪl! aɪ wɒnt tuː teɪk ə ˈpɪktʃə wɪð maɪ njuː ˈkæmərə/",
    hint: "Used for taking photographs. 📷",
  },
  {
    id: 43,
    displaySentence: "Please open the ___ to let some fresh air in.",
    fullSentence: "Please open the window to let some fresh air in.",
    answer: "window",
    options: ["door", "window", "book", "box"],
    translation: "Làm ơn mở cửa sổ để đón chút không khí trong lành.",
    ipa: "/pliːz ˈəʊpən ðə ˈwɪndəʊ tuː lɛt sʌm frɛʃ eər ɪn/",
    hint: "An opening in a wall made of glass. 🪟",
  },
  {
    id: 44,
    displaySentence: "Please sit down on this comfortable ___.",
    fullSentence: "Please sit down on this comfortable chair.",
    answer: "chair",
    options: ["table", "desk", "chair", "bed"],
    translation: "Mời bạn ngồi xuống chiếc ghế thoải mái này.",
    ipa: "/pliːz sɪt daʊn ɒn ðɪs ˈkʌmftəbl tʃeə/",
    hint: "A piece of furniture for one person to sit on. 🪑",
  },
  {
    id: 45,
    displaySentence: "I am so tired, I just want to lie in my ___.",
    fullSentence: "I am so tired, I just want to lie in my bed.",
    answer: "bed",
    options: ["sofa", "bed", "floor", "bath"],
    translation: "Tôi mệt quá, tôi chỉ muốn nằm trên giường của mình.",
    ipa: "/aɪ æm səʊ ˈtaɪəd, aɪ dʒʌst wɒnt tuː laɪ ɪn maɪ bɛd/",
    hint: "Where you sleep at night. 🛏️",
  },
  {
    id: 46,
    displaySentence: "I take the yellow ___ to get to the city center.",
    fullSentence: "I take the yellow bus to get to the city center.",
    answer: "bus",
    options: ["train", "taxi", "bus", "bike"],
    translation: "Tôi đi chuyến xe buýt màu vàng để đến trung tâm thành phố.",
    ipa: "/aɪ teɪk ðə ˈjɛləʊ bʌs tuː ɡɛt tuː ðə ˈsɪti ˈsɛntə/",
    hint: "A large public vehicle. 🚌",
  },
  {
    id: 47,
    displaySentence: "The ___ is arriving at the station in five minutes.",
    fullSentence: "The train is arriving at the station in five minutes.",
    answer: "train",
    options: ["plane", "car", "train", "ship"],
    translation: "Chuyến tàu sẽ đến ga trong năm phút nữa.",
    ipa: "/ðə treɪn ɪz əˈraɪvɪŋ æt ðə ˈsteɪʃən ɪn faɪv ˈmɪnɪts/",
    hint: "It travels on tracks. 🚆",
  },
  {
    id: 48,
    displaySentence: "We collected beautiful shells at the ___ yesterday.",
    fullSentence: "We collected beautiful shells at the sea yesterday.",
    answer: "sea",
    options: ["mountain", "lake", "sea", "forest"],
    translation: "Chúng tôi đã thu thập những vỏ ốc tuyệt đẹp ở biển hôm qua.",
    ipa: "/wiː kəˈlɛktɪd ˈbjuːtɪfʊl ʃɛlz æt ðə siː ˈjɛstədeɪ/",
    hint: "A large body of saltwater. 🌊",
  },
  {
    id: 49,
    displaySentence: "The Amazon is the second longest ___ in the world.",
    fullSentence: "The Amazon is the second longest river in the world.",
    answer: "river",
    options: ["lake", "river", "ocean", "pond"],
    translation: "Amazon là con sông dài thứ hai trên thế giới.",
    ipa: "/ði ˈæməzən ɪz ðə ˈsɛkənd ˈlɒŋɡɪst ˈrɪvər ɪn ðə wɜːld/",
    hint: "A large natural stream of water flowing to the sea. 🏞️",
  },
  {
    id: 50,
    displaySentence: "Can you look at the ___ to find out where we are?",
    fullSentence: "Can you look at the map to find out where we are?",
    answer: "map",
    options: ["book", "map", "clock", "menu"],
    translation: "Bạn có thể xem bản đồ để biết chúng ta đang ở đâu không?",
    ipa: "/kæn juː lʊk æt ðə mæp tuː faɪnd aʊt weə wiː ɑː/",
    hint: "A drawing of an area showing roads and places. 🗺️",
  },
  {
    id: 51,
    displaySentence: "She painted a beautiful ___ of the mountains.",
    fullSentence: "She painted a beautiful picture of the mountains.",
    answer: "picture",
    options: ["song", "story", "picture", "movie"],
    translation: "Cô ấy đã vẽ một bức tranh tuyệt đẹp về những ngọn núi.",
    ipa: "/ʃiː ˈpeɪntɪd ə ˈbjuːtɪfʊl ˈpɪktʃər əv ðə ˈmaʊntɪnz/",
    hint: "A painting or drawing. 🖼️",
  },
  {
    id: 52,
    displaySentence: "Click the left button on your ___ to open the link.",
    fullSentence: "Click the left button on your mouse to open the link.",
    answer: "mouse",
    options: ["screen", "mouse", "speaker", "keyboard"],
    translation: "Nhấp vào nút trái trên chuột của bạn để mở liên kết.",
    ipa: "/klɪk ðə lɛft ˈbʌtn ɒn jɔː maʊs tuː ˈəʊpən ðə lɪŋk/",
    hint: "A computer pointing device. 🖱️",
  },
  {
    id: 53,
    displaySentence: "My computer ___ is broken, I can't type anything.",
    fullSentence: "My computer keyboard is broken, I can't type anything.",
    answer: "keyboard",
    options: ["screen", "battery", "mouse", "keyboard"],
    translation: "Bàn phím máy tính của tôi bị hỏng, tôi không thể gõ gì cả.",
    ipa: "/maɪ kəmˈpjuːtə ˈkiːbɔːd ɪz ˈbrəʊkən, aɪ kɑːnt taɪp ˈɛnɪθɪŋ/",
    hint: "It has letters and numbers for typing. ⌨️",
  },
  {
    id: 54,
    displaySentence: "Would you like a ___ of orange juice?",
    fullSentence: "Would you like a glass of orange juice?",
    answer: "glass",
    options: ["plate", "glass", "bowl", "fork"],
    translation: "Bạn có muốn một ly nước cam không?",
    ipa: "/wʊd juː laɪk ə ɡlɑːs əv ˈɒrɪndʒ dʒuːs/",
    hint: "A drinking container made of glass. 🥛",
  },
  {
    id: 55,
    displaySentence: "Put the slice of pizza on the ___, please.",
    fullSentence: "Put the slice of pizza on the plate, please.",
    answer: "plate",
    options: ["cup", "plate", "spoon", "knife"],
    translation: "Làm ơn đặt lát pizza lên đĩa.",
    ipa: "/pʊt ðə slaɪs əv ˈpiːtsə ɒn ðə pleɪt, pliːz/",
    hint: "A flat dish used for holding food. 🍽️",
  },
  {
    id: 56,
    displaySentence: "He wore a white ___ and a black tie to the meeting.",
    fullSentence: "He wore a white shirt and a black tie to the meeting.",
    answer: "shirt",
    options: ["shoe", "hat", "shirt", "sock"],
    translation:
      "Anh ấy mặc một chiếc áo sơ mi trắng và đeo cà vạt đen đến buổi họp.",
    ipa: "/hiː wɔːr ə waɪt ʃɜːt ænd ə blæk taɪ tuː ðə ˈmiːtɪŋ/",
    hint: "A piece of clothing for the upper body. 👔",
  },
  {
    id: 57,
    displaySentence: "These jeans are my favorite pair of ___.",
    fullSentence: "These jeans are my favorite pair of pants.",
    answer: "pants",
    options: ["pants", "shirts", "gloves", "jackets"],
    translation: "Quần jean này là chiếc quần yêu thích của tôi.",
    ipa: "/ðiːz dʒiːnz ɑː maɪ ˈfeɪvərɪt peər əv pænts/",
    hint: "Clothing that covers the legs. 👖",
  },
  {
    id: 58,
    displaySentence: "You should wear a ___ to protect your head from the sun.",
    fullSentence: "You should wear a hat to protect your head from the sun.",
    answer: "hat",
    options: ["scarf", "ring", "hat", "belt"],
    translation: "Bạn nên đội mũ để bảo vệ đầu khỏi ánh nắng mặt trời.",
    ipa: "/juː ʃʊd weər ə hæt tuː prəˈtɛkt jɔː hɛd frɒm ðə sʌn/",
    hint: "Worn on the head. 🧢",
  },
  {
    id: 59,
    displaySentence: "I like to eat my soup with a warm slice of ___.",
    fullSentence: "I like to eat my soup with a warm slice of bread.",
    answer: "bread",
    options: ["meat", "bread", "milk", "cheese"],
    translation: "Tôi thích ăn súp với một lát bánh mì ấm.",
    ipa: "/aɪ laɪk tuː iːt maɪ suːp wɪð ə wɔːm slaɪs əv brɛd/",
    hint: "A baked food made of flour and water. 🍞",
  },
  {
    id: 60,
    displaySentence: "Vegetarians do not eat ___ or fish.",
    fullSentence: "Vegetarians do not eat meat or fish.",
    answer: "meat",
    options: ["vegetables", "fruit", "meat", "rice"],
    translation: "Người ăn chay không ăn thịt hoặc cá.",
    ipa: "/ˌvɛdʒɪˈteərɪənz duː nɒt iːt miːt ɔː fɪʃ/",
    hint: "Food that comes from animals. 🥩",
  },
  {
    id: 61,
    displaySentence: "An ___ a day keeps the doctor away.",
    fullSentence: "An apple a day keeps the doctor away.",
    answer: "apple",
    options: ["banana", "apple", "grape", "orange"],
    translation: "Mỗi ngày một quả táo sẽ giúp bạn tránh xa bác sĩ.",
    ipa: "/ən ˈæpl ə deɪ kiːps ðə ˈdɒktər əˈweɪ/",
    hint: "A crunchy red or green fruit. 🍎",
  },
  {
    id: 62,
    displaySentence: "I love drinking freshly squeezed ___ juice.",
    fullSentence: "I love drinking freshly squeezed orange juice.",
    answer: "orange",
    options: ["apple", "grape", "orange", "lemon"],
    translation: "Tôi rất thích uống nước cam vắt tươi.",
    ipa: "/aɪ lʌv ˈdrɪŋkɪŋ ˈfrɛʃli skwiːzd ˈɒrɪndʒ dʒuːs/",
    hint: "A round, sweet citrus fruit. 🍊",
  },
  {
    id: 63,
    displaySentence: "Look at that bright shooting ___ in the night sky!",
    fullSentence: "Look at that bright shooting star in the night sky!",
    answer: "star",
    options: ["moon", "sun", "cloud", "star"],
    translation: "Nhìn ngôi sao băng sáng chói trên bầu trời đêm kìa!",
    ipa: "/lʊk æt ðæt braɪt ˈʃuːtɪŋ stɑːr ɪn ðə naɪt skaɪ/",
    hint: "A tiny light shining in the dark sky. ⭐",
  },
  {
    id: 64,
    displaySentence: "The full ___ looks beautiful and bright tonight.",
    fullSentence: "The full moon looks beautiful and bright tonight.",
    answer: "moon",
    options: ["sun", "star", "moon", "cloud"],
    translation: "Mặt trăng tròn trông thật đẹp và sáng đêm nay.",
    ipa: "/ðə fʊl muːn lʊks ˈbjuːtɪfʊl ænd braɪt təˈnaɪt/",
    hint: "It shines in the sky at night. 🌕",
  },
  {
    id: 65,
    displaySentence: "Children love to build a snowman when the ___ falls.",
    fullSentence: "Children love to build a snowman when the snow falls.",
    answer: "snow",
    options: ["rain", "snow", "sand", "wind"],
    translation: "Trẻ em thích đắp người tuyết khi tuyết rơi.",
    ipa: "/ˈtʃɪldrən lʌv tuː bɪld ə ˈsnəʊmæn wɛn ðə snəʊ fɔːlz/",
    hint: "Soft, white frozen water flakes. ❄️",
  },
  {
    id: 66,
    displaySentence: "The strong ___ blew away my umbrella.",
    fullSentence: "The strong wind blew away my umbrella.",
    answer: "wind",
    options: ["rain", "wind", "sun", "cloud"],
    translation: "Gió mạnh đã thổi bay chiếc ô của tôi.",
    ipa: "/ðə strɒŋ wɪnd bluː əˈweɪ maɪ ʌmˈbrɛlə/",
    hint: "Moving air. 🌬️",
  },
  {
    id: 67,
    displaySentence: "We sat around the camp ___ to stay warm.",
    fullSentence: "We sat around the camp fire to stay warm.",
    answer: "fire",
    options: ["fire", "water", "tree", "rock"],
    translation: "Chúng tôi ngồi quanh đống lửa trại để sưởi ấm.",
    ipa: "/wiː sæt əˈraʊnd ðə kæmp ˈfaɪə tuː steɪ wɔːm/",
    hint: "It gives out heat and light. 🔥",
  },
  {
    id: 68,
    displaySentence: "Students go to ___ five days a week.",
    fullSentence: "Students go to school five days a week.",
    answer: "school",
    options: ["hospital", "school", "bank", "restaurant"],
    translation: "Học sinh đến trường năm ngày một tuần.",
    ipa: "/ˈstjuːdənts ɡəʊ tuː skuːl faɪv deɪz ə wiːk/",
    hint: "A place for learning. 🏫",
  },
  {
    id: 69,
    displaySentence: "I need to go to the ___ to withdraw some money.",
    fullSentence: "I need to go to the bank to withdraw some money.",
    answer: "bank",
    options: ["park", "zoo", "bank", "library"],
    translation: "Tôi cần đến ngân hàng để rút một ít tiền.",
    ipa: "/aɪ niːd tuː ɡəʊ tuː ðə bæŋk tuː wɪðˈdrɔː sʌm ˈmʌni/",
    hint: "A place to keep money safely. 🏦",
  },
  {
    id: 70,
    displaySentence: "My mother buys fresh vegetables at the local ___.",
    fullSentence: "My mother buys fresh vegetables at the local market.",
    answer: "market",
    options: ["market", "museum", "cinema", "hospital"],
    translation: "Mẹ tôi mua rau tươi ở khu chợ địa phương.",
    ipa: "/maɪ ˈmʌðə baɪz frɛʃ ˈvɛdʒtəbəlz æt ðə ˈləʊkəl ˈmɑːkɪt/",
    hint: "A place where people buy and sell goods. 🛒",
  },
  {
    id: 71,
    displaySentence: "We had a delicious dinner at an Italian ___.",
    fullSentence: "We had a delicious dinner at an Italian restaurant.",
    answer: "restaurant",
    options: ["restaurant", "library", "school", "factory"],
    translation: "Chúng tôi đã có một bữa tối ngon miệng tại một nhà hàng Ý.",
    ipa: "/wiː hæd ə dɪˈlɪʃəs ˈdɪnər æt ən ɪˈtæliən ˈrɛstrɒnt/",
    hint: "A place where you pay to eat food. 🍝",
  },
  {
    id: 72,
    displaySentence: "We saw dinosaur bones at the natural history ___.",
    fullSentence: "We saw dinosaur bones at the natural history museum.",
    answer: "museum",
    options: ["museum", "bank", "supermarket", "stadium"],
    translation:
      "Chúng tôi đã thấy xương khủng long tại bảo tàng lịch sử tự nhiên.",
    ipa: "/wiː sɔː ˈdaɪnəsɔː bəʊnz æt ðə ˈnætʃrəl ˈhɪstəri mju(ː)ˈzɪəm/",
    hint: "A building where historical objects are kept. 🏛️",
  },
  {
    id: 73,
    displaySentence: "He was very ___ when someone broke his toy.",
    fullSentence: "He was very angry when someone broke his toy.",
    answer: "angry",
    options: ["happy", "angry", "thirsty", "tired"],
    translation: "Cậu bé rất tức giận khi có người làm hỏng đồ chơi của mình.",
    ipa: "/hiː wɒz ˈvɛri ˈæŋɡri wɛn ˈsʌmwʌn brəʊk hɪz tɔɪ/",
    hint: "Feeling strong displeasure. 😠",
  },
  {
    id: 74,
    displaySentence: "She felt ___ because her dog was sick.",
    fullSentence: "She felt sad because her dog was sick.",
    answer: "sad",
    options: ["excited", "sad", "happy", "funny"],
    translation: "Cô ấy cảm thấy buồn vì chú chó của cô bị ốm.",
    ipa: "/ʃiː fɛlt sæd bɪˈkɒz hɜː dɒɡ wɒz sɪk/",
    hint: "Feeling sorrow or unhappiness. 😢",
  },
  {
    id: 75,
    displaySentence: "After a long day of work, I am very ___.",
    fullSentence: "After a long day of work, I am very tired.",
    answer: "tired",
    options: ["hungry", "tired", "fast", "angry"],
    translation: "Sau một ngày dài làm việc, tôi rất mệt mỏi.",
    ipa: "/ˈɑːftər ə lɒŋ deɪ əv wɜːk, aɪ æm ˈvɛri ˈtaɪəd/",
    hint: "Needing rest or sleep. 🥱",
  },
  {
    id: 76,
    displaySentence: "It is freezing outside, I feel very ___.",
    fullSentence: "It is freezing outside, I feel very cold.",
    answer: "cold",
    options: ["hot", "warm", "cold", "happy"],
    translation: "Bên ngoài trời đang đóng băng, tôi cảm thấy rất lạnh.",
    ipa: "/ɪt ɪz ˈfriːzɪŋ ˌaʊtˈsaɪd, aɪ fiːl ˈvɛri kəʊld/",
    hint: "Having a low temperature. 🥶",
  },
  {
    id: 77,
    displaySentence: "The weather is so ___ today in the summer.",
    fullSentence: "The weather is so hot today in the summer.",
    answer: "hot",
    options: ["cold", "hot", "rainy", "snowy"],
    translation: "Thời tiết hôm nay thật nóng bức vào mùa hè.",
    ipa: "/ðə ˈwɛðə ɪz səʊ hɒt təˈdeɪ ɪn ðə ˈsʌmə/",
    hint: "Having a high temperature. 🥵",
  },
  {
    id: 78,
    displaySentence: "Cheetahs are known to run very ___.",
    fullSentence: "Cheetahs are known to run very fast.",
    answer: "fast",
    options: ["slow", "quiet", "fast", "loud"],
    translation: "Báo đốm được biết đến là chạy rất nhanh.",
    ipa: "/ˈtʃiːtəz ɑː nəʊn tuː rʌn ˈvɛri fɑːst/",
    hint: "Moving at high speed. ⚡",
  },
  {
    id: 79,
    displaySentence: "Turtles are animals that walk very ___.",
    fullSentence: "Turtles are animals that walk very slow.",
    answer: "slow",
    options: ["fast", "slow", "quick", "hard"],
    translation: "Rùa là loài động vật đi bộ rất chậm.",
    ipa: "/ˈtɜːtlz ɑː ˈænɪməlz ðæt wɔːk ˈvɛri sləʊ/",
    hint: "Moving at a low speed. 🐢",
  },
  {
    id: 80,
    displaySentence: "The sunset over the beach was extremely ___.",
    fullSentence: "The sunset over the beach was extremely beautiful.",
    answer: "beautiful",
    options: ["ugly", "bad", "beautiful", "scary"],
    translation: "Hoàng hôn trên bãi biển thật vô cùng xinh đẹp.",
    ipa: "/ðə ˈsʌnsɛt ˈəʊvə ðə biːtʃ wɒz ɪkˈstriːmli ˈbjuːtɪfʊl/",
    hint: "Pleasing to the eye. ✨",
  },
  {
    id: 81,
    displaySentence: "I always drink a glass of ___ before going to bed.",
    fullSentence: "I always drink a glass of milk before going to bed.",
    answer: "milk",
    options: ["milk", "bread", "meat", "rice"],
    translation: "Tôi luôn uống một ly sữa trước khi đi ngủ.",
    ipa: "/aɪ ˈɔːlweɪz drɪŋk ə ɡlɑːs əv mɪlk bɪˈfɔː ˈɡəʊɪŋ tuː bɛd/",
    hint: "A white liquid produced by cows. 🥛",
  },
  {
    id: 82,
    displaySentence: "She had a boiled ___ and some toast for breakfast.",
    fullSentence: "She had a boiled egg and some toast for breakfast.",
    answer: "egg",
    options: ["egg", "apple", "fish", "cake"],
    translation: "Cô ấy ăn một quả trứng luộc và bánh mì nướng cho bữa sáng.",
    ipa: "/ʃiː hæd ə bɔɪld ɛɡ ænd sʌm təʊst fɔː ˈbrɛkfəst/",
    hint: "Laid by birds and often eaten for breakfast. 🥚",
  },
  {
    id: 83,
    displaySentence: "People in Asia eat a lot of ___ every day.",
    fullSentence: "People in Asia eat a lot of rice every day.",
    answer: "rice",
    options: ["rice", "bread", "potato", "pasta"],
    translation: "Người dân ở Châu Á ăn rất nhiều gạo mỗi ngày.",
    ipa: "/ˈpiːpl ɪn ˈeɪʒə iːt ə lɒt əv raɪs ˈɛvri deɪ/",
    hint: "Small white grains cooked by boiling. 🍚",
  },
  {
    id: 84,
    displaySentence: "We caught a big ___ while fishing in the lake.",
    fullSentence: "We caught a big fish while fishing in the lake.",
    answer: "fish",
    options: ["bird", "dog", "fish", "cat"],
    translation: "Chúng tôi đã bắt được một con cá lớn khi câu ở hồ.",
    ipa: "/wiː kɔːt ə bɪɡ fɪʃ waɪl ˈfɪʃɪŋ ɪn ðə leɪk/",
    hint: "An animal that lives and breathes in water. 🐟",
  },
  {
    id: 85,
    displaySentence: "My grandmother makes the best fried ___ in town.",
    fullSentence: "My grandmother makes the best fried chicken in town.",
    answer: "chicken",
    options: ["pork", "beef", "chicken", "fish"],
    translation: "Bà tôi làm món gà rán ngon nhất thị trấn.",
    ipa: "/maɪ ˈɡrænˌmʌðə meɪks ðə bɛst fraɪd ˈtʃɪkɪn ɪn taʊn/",
    hint: "A bird kept for its eggs and meat. 🍗",
  },
  {
    id: 86,
    displaySentence: "He blew out the candles on his birthday ___.",
    fullSentence: "He blew out the candles on his birthday cake.",
    answer: "cake",
    options: ["cake", "bread", "candy", "cookie"],
    translation: "Anh ấy đã thổi nến trên chiếc bánh sinh nhật của mình.",
    ipa: "/hiː bluː aʊt ðə ˈkændlz ɒn hɪz ˈbɜːθdeɪ keɪk/",
    hint: "A sweet baked food. 🎂",
  },
  {
    id: 87,
    displaySentence: "The soup is tasteless. Can you pass the ___, please?",
    fullSentence: "The soup is tasteless. Can you pass the salt, please?",
    answer: "salt",
    options: ["sugar", "pepper", "salt", "water"],
    translation: "Món súp nhạt quá. Bạn làm ơn đưa muối cho tôi được không?",
    ipa: "/ðə suːp ɪz ˈteɪstlɪs. kæn juː pɑːs ðə sɒlt, pliːz/",
    hint: "A white substance used to flavor food. 🧂",
  },
  {
    id: 88,
    displaySentence: "I need to add some ___ to my coffee to make it sweet.",
    fullSentence: "I need to add some sugar to my coffee to make it sweet.",
    answer: "sugar",
    options: ["salt", "water", "milk", "sugar"],
    translation: "Tôi cần thêm chút đường vào cà phê để làm cho nó ngọt.",
    ipa: "/aɪ niːd tuː æd sʌm ˈʃʊɡə tuː maɪ ˈkɒfi tuː meɪk ɪt swiːt/",
    hint: "Makes things taste sweet. 🍬",
  },
  {
    id: 89,
    displaySentence:
      "English people love drinking a cup of ___ in the afternoon.",
    fullSentence: "English people love drinking a cup of tea in the afternoon.",
    answer: "tea",
    options: ["coffee", "water", "tea", "beer"],
    translation: "Người Anh thích uống một tách trà vào buổi chiều.",
    ipa: "/ˈɪŋɡlɪʃ ˈpiːpl lʌv ˈdrɪŋkɪŋ ə kʌp əv tiː ɪn ði ˌɑːftəˈnuːn/",
    hint: "A hot drink made by infusing dried leaves. 🍵",
  },
  {
    id: 90,
    displaySentence: "Mice are known to love eating ___.",
    fullSentence: "Mice are known to love eating cheese.",
    answer: "cheese",
    options: ["meat", "bread", "cheese", "apple"],
    translation: "Chuột được biết đến là rất thích ăn phô mai.",
    ipa: "/maɪs ɑː nəʊn tuː lʌv ˈiːtɪŋ tʃiːz/",
    hint: "A dairy product made from milk. 🧀",
  },
  {
    id: 91,
    displaySentence: "The ___ barks loudly when a stranger comes near.",
    fullSentence: "The dog barks loudly when a stranger comes near.",
    answer: "dog",
    options: ["cat", "dog", "cow", "bird"],
    translation: "Con chó sủa to khi có người lạ đến gần.",
    ipa: "/ðə dɒɡ bɑːks ˈlaʊdli wɛn ə ˈstreɪndʒə kʌmz nɪə/",
    hint: "Man's best friend. 🐕",
  },
  {
    id: 92,
    displaySentence: "I saw a beautiful little ___ flying in the sky.",
    fullSentence: "I saw a beautiful little bird flying in the sky.",
    answer: "bird",
    options: ["fish", "bird", "dog", "cat"],
    translation: "Tôi thấy một chú chim nhỏ xinh đẹp đang bay trên bầu trời.",
    ipa: "/aɪ sɔː ə ˈbjuːtɪfʊl ˈlɪtl bɜːd ˈflaɪɪŋ ɪn ðə skaɪ/",
    hint: "An animal with wings and feathers. 🐦",
  },
  {
    id: 93,
    displaySentence: "The farmer rides his ___ across the large field.",
    fullSentence: "The farmer rides his horse across the large field.",
    answer: "horse",
    options: ["cow", "pig", "horse", "sheep"],
    translation: "Người nông dân cưỡi ngựa của mình băng qua cánh đồng lớn.",
    ipa: "/ðə ˈfɑːmə raɪdz hɪz hɔːs əˈkrɒs ðə lɑːdʒ fiːld/",
    hint: "A large animal you can ride. 🐎",
  },
  {
    id: 94,
    displaySentence: "That black and white ___ gives us a lot of milk.",
    fullSentence: "That black and white cow gives us a lot of milk.",
    answer: "cow",
    options: ["cow", "pig", "horse", "dog"],
    translation: "Con bò đen trắng đó cho chúng ta rất nhiều sữa.",
    ipa: "/ðæt blæk ænd waɪt kaʊ ɡɪvz ʌs ə lɒt əv mɪlk/",
    hint: "It says moo. 🐄",
  },
  {
    id: 95,
    displaySentence: "The pink ___ is rolling in the mud to stay cool.",
    fullSentence: "The pink pig is rolling in the mud to stay cool.",
    answer: "pig",
    options: ["cat", "pig", "bird", "fish"],
    translation: "Con lợn hồng đang lăn trong bùn để làm mát.",
    ipa: "/ðə pɪŋk pɪɡ ɪz ˈrəʊlɪŋ ɪn ðə mʌd tuː steɪ kuːl/",
    hint: "An animal kept for pork. 🐖",
  },
  {
    id: 96,
    displaySentence: "The farmer sheared the ___ to get its wool.",
    fullSentence: "The farmer sheared the sheep to get its wool.",
    answer: "sheep",
    options: ["dog", "sheep", "cat", "horse"],
    translation: "Người nông dân xén lông cừu để lấy len.",
    ipa: "/ðə ˈfɑːmə ʃɪəd ðə ʃiːp tuː ɡɛt ɪts wʊl/",
    hint: "It gives us wool and says baa. 🐑",
  },
  {
    id: 97,
    displaySentence: "We saw a funny ___ swinging from the trees at the zoo.",
    fullSentence: "We saw a funny monkey swinging from the trees at the zoo.",
    answer: "monkey",
    options: ["elephant", "tiger", "monkey", "lion"],
    translation: "Chúng tôi đã thấy một con khỉ vui nhộn đu trên cây ở sở thú.",
    ipa: "/wiː sɔː ə ˈfʌni ˈmʌŋki ˈswɪŋɪŋ frɒm ðə triːz æt ðə zuː/",
    hint: "An animal that loves bananas. 🐒",
  },
  {
    id: 98,
    displaySentence: "Be careful! There is a poisonous ___ in the grass.",
    fullSentence: "Be careful! There is a poisonous snake in the grass.",
    answer: "snake",
    options: ["bird", "snake", "mouse", "fish"],
    translation: "Cẩn thận đấy! Có một con rắn độc trong bãi cỏ.",
    ipa: "/biː ˈkeəfʊl! ðeər ɪz ə ˈpɔɪzənəs sneɪk ɪn ðə ɡrɑːs/",
    hint: "A long reptile with no legs. 🐍",
  },
  {
    id: 99,
    displaySentence: "The large brown ___ is sleeping in its cave.",
    fullSentence: "The large brown bear is sleeping in its cave.",
    answer: "bear",
    options: ["rabbit", "bear", "fox", "deer"],
    translation: "Con gấu nâu to lớn đang ngủ trong hang của nó.",
    ipa: "/ðə lɑːdʒ braʊn beər ɪz ˈsliːpɪŋ ɪn ɪts keɪv/",
    hint: "A large, heavy animal with thick fur. 🐻",
  },
  {
    id: 100,
    displaySentence: "The ___ is the largest land animal on Earth.",
    fullSentence: "The elephant is the largest land animal on Earth.",
    answer: "elephant",
    options: ["tiger", "elephant", "giraffe", "hippo"],
    translation: "Voi là loài động vật trên cạn lớn nhất Trái đất.",
    ipa: "/ði ˈɛlɪfənt ɪz ðə ˈlɑːdʒɪst lænd ˈænɪməl ɒn ɜːθ/",
    hint: "Has a long trunk and big ears. 🐘",
  },
  {
    id: 101,
    displaySentence:
      "The ___ examined the patient and prescribed some medicine.",
    fullSentence:
      "The doctor examined the patient and prescribed some medicine.",
    answer: "doctor",
    options: ["teacher", "farmer", "doctor", "singer"],
    translation: "Bác sĩ đã khám cho bệnh nhân và kê một ít thuốc.",
    ipa: "/ðə ˈdɒktər ɪɡˈzæmɪnd ðə ˈpeɪʃənt ænd prɪsˈkraɪbd sʌm ˈmɛdsɪn/",
    hint: "Treats sick people. 👨‍⚕️",
  },
  {
    id: 102,
    displaySentence: "The ___ helped the doctor care for the injured man.",
    fullSentence: "The nurse helped the doctor care for the injured man.",
    answer: "nurse",
    options: ["nurse", "police", "driver", "chef"],
    translation: "Nữ y tá đã giúp bác sĩ chăm sóc người đàn ông bị thương.",
    ipa: "/ðə nɜːs hɛlpt ðə ˈdɒktə keə fɔː ði ˈɪndʒəd mæn/",
    hint: "Helps doctors in a hospital. 👩‍⚕️",
  },
  {
    id: 103,
    displaySentence: "The ___ caught the thief who stole the bag.",
    fullSentence: "The police caught the thief who stole the bag.",
    answer: "police",
    options: ["teacher", "police", "farmer", "worker"],
    translation: "Cảnh sát đã bắt được tên trộm ăn cắp chiếc túi.",
    ipa: "/ðə pəˈliːs kɔːt ðə θiːf huː stəʊl ðə bæɡ/",
    hint: "Protects people and catches criminals. 👮",
  },
  {
    id: 104,
    displaySentence: "The bus ___ drove us safely to the destination.",
    fullSentence: "The bus driver drove us safely to the destination.",
    answer: "driver",
    options: ["driver", "pilot", "doctor", "singer"],
    translation: "Tài xế xe buýt đã lái xe đưa chúng tôi đến đích an toàn.",
    ipa: "/ðə bʌs ˈdraɪvə drəʊv ʌs ˈseɪfli tuː ðə ˌdɛstɪˈneɪʃən/",
    hint: "A person who drives a vehicle. 🚌",
  },
  {
    id: 105,
    displaySentence: "My favorite ___ released a new album yesterday.",
    fullSentence: "My favorite singer released a new album yesterday.",
    answer: "singer",
    options: ["actor", "singer", "writer", "dancer"],
    translation:
      "Ca sĩ yêu thích của tôi đã phát hành một album mới vào ngày hôm qua.",
    ipa: "/maɪ ˈfeɪvərɪt ˈsɪŋə rɪˈliːst ə njuː ˈælbəm ˈjɛstədeɪ/",
    hint: "Someone who sings professionally. 🎤",
  },
  {
    id: 106,
    displaySentence: "The ___ grows vegetables and raises animals.",
    fullSentence: "The farmer grows vegetables and raises animals.",
    answer: "farmer",
    options: ["farmer", "teacher", "doctor", "pilot"],
    translation: "Người nông dân trồng rau và chăn nuôi động vật.",
    ipa: "/ðə ˈfɑːmə ɡrəʊz ˈvɛdʒtəbəlz ænd ˈreɪzɪz ˈænɪməlz/",
    hint: "Works on a farm. 🧑‍🌾",
  },
  {
    id: 107,
    displaySentence: "The ___ is studying hard for the final exam.",
    fullSentence: "The student is studying hard for the final exam.",
    answer: "student",
    options: ["teacher", "student", "worker", "chef"],
    translation: "Học sinh đang học hành chăm chỉ cho kỳ thi cuối kỳ.",
    ipa: "/ðə ˈstjuːdənt ɪz ˈstʌdiɪŋ hɑːd fɔː ðə ˈfaɪnəl ɪɡˈzæm/",
    hint: "A person who is learning at a school. 🎒",
  },
  {
    id: 108,
    displaySentence: "The construction ___ is building a new house.",
    fullSentence: "The construction worker is building a new house.",
    answer: "worker",
    options: ["worker", "singer", "pilot", "doctor"],
    translation: "Công nhân xây dựng đang xây một ngôi nhà mới.",
    ipa: "/ðə kənˈstrʌkʃən ˈwɜːkər ɪz ˈbɪldɪŋ ə njuː haʊs/",
    hint: "Does physical or industrial work. 👷",
  },
  {
    id: 109,
    displaySentence: "The ___ flew the airplane through the storm safely.",
    fullSentence: "The pilot flew the airplane through the storm safely.",
    answer: "pilot",
    options: ["driver", "pilot", "farmer", "police"],
    translation: "Phi công đã lái máy bay qua cơn bão một cách an toàn.",
    ipa: "/ðə ˈpaɪlət fluː ði ˈeəpleɪn θruː ðə stɔːm ˈseɪfli/",
    hint: "Flies airplanes. ✈️",
  },
  {
    id: 110,
    displaySentence: "The head ___ at the restaurant cooks amazing pasta.",
    fullSentence: "The head chef at the restaurant cooks amazing pasta.",
    answer: "chef",
    options: ["doctor", "student", "chef", "nurse"],
    translation: "Bếp trưởng tại nhà hàng nấu món mì Ý tuyệt vời.",
    ipa: "/ðə hɛd ʃɛf æt ðə ˈrɛstrɒnt kʊks əˈmeɪzɪŋ ˈpæstə/",
    hint: "A professional cook. 👨‍🍳",
  },
  {
    id: 111,
    displaySentence: "We bought a new leather ___ for our living room.",
    fullSentence: "We bought a new leather sofa for our living room.",
    answer: "sofa",
    options: ["bed", "sofa", "table", "door"],
    translation: "Chúng tôi đã mua một chiếc ghế sofa da mới cho phòng khách.",
    ipa: "/wiː bɔːt ə njuː ˈlɛðə ˈsəʊfə fɔː ˈaʊə ˈlɪvɪŋ ruːm/",
    hint: "A comfortable seat for two or more people. 🛋️",
  },
  {
    id: 112,
    displaySentence: "We like to watch the news on the ___ every evening.",
    fullSentence: "We like to watch the news on the TV every evening.",
    answer: "TV",
    options: ["radio", "TV", "computer", "phone"],
    translation: "Chúng tôi thích xem tin tức trên TV mỗi tối.",
    ipa: "/wiː laɪk tuː wɒtʃ ðə njuːz ɒn ðə ˌtiːˈviː ˈɛvri ˈiːvnɪŋ/",
    hint: "Shows moving pictures and sound. 📺",
  },
  {
    id: 113,
    displaySentence: "Put the milk in the ___ so it stays fresh.",
    fullSentence: "Put the milk in the fridge so it stays fresh.",
    answer: "fridge",
    options: ["oven", "fridge", "table", "sink"],
    translation: "Hãy để sữa vào tủ lạnh để nó được tươi lâu.",
    ipa: "/pʊt ðə mɪlk ɪn ðə frɪdʒ səʊ ɪt steɪz frɛʃ/",
    hint: "Keeps food cold. 🧊",
  },
  {
    id: 114,
    displaySentence: "I take a quick ___ every morning before work.",
    fullSentence: "I take a quick shower every morning before work.",
    answer: "shower",
    options: ["bath", "shower", "sleep", "walk"],
    translation: "Tôi tắm vòi sen nhanh mỗi sáng trước khi đi làm.",
    ipa: "/aɪ teɪk ə kwɪk ˈʃaʊər ˈɛvri ˈmɔːnɪŋ bɪˈfɔː wɜːk/",
    hint: "Washing yourself under a spray of water. 🚿",
  },
  {
    id: 115,
    displaySentence: "The cat climbed up onto the ___ of the house.",
    fullSentence: "The cat climbed up onto the roof of the house.",
    answer: "roof",
    options: ["floor", "door", "roof", "window"],
    translation: "Con mèo trèo lên mái nhà.",
    ipa: "/ðə kæt klaɪmd ʌp ˈɒntʊ ðə ruːf əv ðə haʊs/",
    hint: "The top cover of a building. 🏠",
  },
  {
    id: 116,
    displaySentence: "We painted the living room ___ a bright blue color.",
    fullSentence: "We painted the living room wall a bright blue color.",
    answer: "wall",
    options: ["wall", "floor", "window", "carpet"],
    translation:
      "Chúng tôi đã sơn bức tường phòng khách một màu xanh lam nhạt.",
    ipa: "/wiː ˈpeɪntɪd ðə ˈlɪvɪŋ ruːm wɔːl ə braɪt bluː ˈkʌlə/",
    hint: "An upright structure that divides rooms. 🧱",
  },
  {
    id: 117,
    displaySentence: "Please take off your shoes so you don't dirty the ___.",
    fullSentence: "Please take off your shoes so you don't dirty the floor.",
    answer: "floor",
    options: ["wall", "ceiling", "door", "floor"],
    translation: "Vui lòng cởi giày để không làm bẩn sàn nhà.",
    ipa: "/pliːz teɪk ɒf jɔː ʃuːz səʊ juː dəʊnt ˈdɜːti ðə flɔː/",
    hint: "The surface of a room that you walk on. 🪵",
  },
  {
    id: 118,
    displaySentence: "He walked up the ___ to get to his bedroom.",
    fullSentence: "He walked up the stairs to get to his bedroom.",
    answer: "stairs",
    options: ["stairs", "windows", "walls", "doors"],
    translation: "Anh ấy bước lên cầu thang để đến phòng ngủ của mình.",
    ipa: "/hiː wɔːkt ʌp ðə steəz tuː ɡɛt tuː hɪz ˈbɛdru(ː)m/",
    hint: "A set of steps leading from one level to another. 🪜",
  },
  {
    id: 119,
    displaySentence: "After washing my face, I dried it with a clean ___.",
    fullSentence: "After washing my face, I dried it with a clean towel.",
    answer: "towel",
    options: ["blanket", "towel", "shirt", "paper"],
    translation: "Sau khi rửa mặt, tôi lau khô bằng một chiếc khăn sạch.",
    ipa: "/ˈɑːftə ˈwɒʃɪŋ maɪ feɪs, aɪ draɪd ɪt wɪð ə kliːn ˈtaʊəl/",
    hint: "Used for drying yourself. 🧣",
  },
  {
    id: 120,
    displaySentence: "Always wash your hands with ___ and water.",
    fullSentence: "Always wash your hands with soap and water.",
    answer: "soap",
    options: ["soap", "sand", "oil", "juice"],
    translation: "Luôn rửa tay bằng xà phòng và nước.",
    ipa: "/ˈɔːlweɪz wɒʃ jɔː hændz wɪð səʊp ænd ˈwɔːtə/",
    hint: "Used with water for washing. 🧼",
  },
  {
    id: 121,
    displaySentence: "We are planning to climb the highest ___ in the country.",
    fullSentence:
      "We are planning to climb the highest mountain in the country.",
    answer: "mountain",
    options: ["hill", "mountain", "valley", "lake"],
    translation:
      "Chúng tôi đang lên kế hoạch leo ngọn núi cao nhất trong nước.",
    ipa: "/wiː ɑː ˈplænɪŋ tuː klaɪm ðə ˈhaɪɪst ˈmaʊntɪn ɪn ðə ˈkʌntri/",
    hint: "A very high hill. ⛰️",
  },
  {
    id: 122,
    displaySentence: "There are many wild animals living in the ___.",
    fullSentence: "There are many wild animals living in the forest.",
    answer: "forest",
    options: ["beach", "forest", "city", "desert"],
    translation: "Có rất nhiều động vật hoang dã sống trong khu rừng.",
    ipa: "/ðeər ɑː ˈmɛni waɪld ˈænɪməlz ˈlɪvɪŋ ɪn ðə ˈfɒrɪst/",
    hint: "A large area covered with trees. 🌲",
  },
  {
    id: 123,
    displaySentence: "We went swimming and relaxed on the sandy ___.",
    fullSentence: "We went swimming and relaxed on the sandy beach.",
    answer: "beach",
    options: ["beach", "forest", "mountain", "farm"],
    translation: "Chúng tôi đã đi bơi và thư giãn trên bãi biển đầy cát.",
    ipa: "/wiː wɛnt ˈswɪmɪŋ ænd rɪˈlækst ɒn ðə ˈsændi biːtʃ/",
    hint: "Next to the sea. 🏖️",
  },
  {
    id: 124,
    displaySentence: "They spent their holiday on a small tropical ___.",
    fullSentence: "They spent their holiday on a small tropical island.",
    answer: "island",
    options: ["island", "lake", "river", "mountain"],
    translation: "Họ đã trải qua kỳ nghỉ trên một hòn đảo nhiệt đới nhỏ.",
    ipa: "/ðeɪ spɛnt ðeə ˈhɒlədeɪ ɒn ə smɔːl ˈtrɒpɪkəl ˈaɪlənd/",
    hint: "Land surrounded by water. 🏝️",
  },
  {
    id: 125,
    displaySentence: "She smelled the beautiful red ___ in the garden.",
    fullSentence: "She smelled the beautiful red flower in the garden.",
    answer: "flower",
    options: ["flower", "tree", "rock", "grass"],
    translation: "Cô ấy ngửi bông hoa đỏ tuyệt đẹp trong vườn.",
    ipa: "/ʃiː smɛlt ðə ˈbjuːtɪfʊl rɛd ˈflaʊər ɪn ðə ˈɡɑːdn/",
    hint: "The colorful part of a plant. 🌹",
  },
  {
    id: 126,
    displaySentence: "The cows are eating green ___ in the field.",
    fullSentence: "The cows are eating green grass in the field.",
    answer: "grass",
    options: ["grass", "meat", "bread", "rocks"],
    translation: "Những con bò đang ăn cỏ xanh trên cánh đồng.",
    ipa: "/ðə kaʊz ɑː ˈiːtɪŋ ɡriːn ɡrɑːs ɪn ðə fiːld/",
    hint: "Green plants that cover the ground. 🌱",
  },
  {
    id: 127,
    displaySentence: "In autumn, every ___ on the tree turns yellow or red.",
    fullSentence: "In autumn, every leaf on the tree turns yellow or red.",
    answer: "leaf",
    options: ["leaf", "branch", "root", "trunk"],
    translation:
      "Vào mùa thu, mỗi chiếc lá trên cây đều chuyển sang màu vàng hoặc đỏ.",
    ipa: "/ɪn ˈɔːtəm, ˈɛvri liːf ɒn ðə triː tɜːnz ˈjɛləʊ ɔː rɛd/",
    hint: "The flat green part of a plant. 🍂",
  },
  {
    id: 128,
    displaySentence: "There is not a single ___ in the sunny blue sky.",
    fullSentence: "There is not a single cloud in the sunny blue sky.",
    answer: "cloud",
    options: ["bird", "cloud", "star", "moon"],
    translation: "Không có một đám mây nào trên bầu trời xanh đầy nắng.",
    ipa: "/ðeər ɪz nɒt ə ˈsɪŋɡl klaʊd ɪn ðə ˈsʌni bluː skaɪ/",
    hint: "A white or gray mass in the sky. ☁️",
  },
  {
    id: 129,
    displaySentence: "I need an umbrella because the ___ is pouring down.",
    fullSentence: "I need an umbrella because the rain is pouring down.",
    answer: "rain",
    options: ["snow", "wind", "rain", "sun"],
    translation: "Tôi cần một chiếc ô vì mưa đang trút xuống.",
    ipa: "/aɪ niːd ən ʌmˈbrɛlə bɪˈkɒz ðə reɪn ɪz ˈpɔːrɪŋ daʊn/",
    hint: "Drops of water from the sky. 🌧️",
  },
  {
    id: 130,
    displaySentence: "The birds are flying high up in the clear blue ___.",
    fullSentence: "The birds are flying high up in the clear blue sky.",
    answer: "sky",
    options: ["sea", "sky", "river", "forest"],
    translation:
      "Những chú chim đang bay vút cao trên bầu trời xanh trong vắt.",
    ipa: "/ðə bɜːdz ɑː ˈflaɪɪŋ haɪ ʌp ɪn ðə klɪə bluː skaɪ/",
    hint: "The space above the earth. 🌌",
  },
  {
    id: 131,
    displaySentence: "She is holding a pen in her right ___.",
    fullSentence: "She is holding a pen in her right hand.",
    answer: "hand",
    options: ["foot", "hand", "head", "leg"],
    translation: "Cô ấy đang cầm một cây bút trên tay phải.",
    ipa: "/ʃiː ɪz ˈhəʊldɪŋ ə pɛn ɪn hɜː raɪt hænd/",
    hint: "Has five fingers. 🖐️",
  },
  {
    id: 132,
    displaySentence: "He kicked the football with his left ___.",
    fullSentence: "He kicked the football with his left foot.",
    answer: "foot",
    options: ["hand", "foot", "arm", "ear"],
    translation: "Anh ấy đã đá quả bóng bằng chân trái.",
    ipa: "/hiː kɪkt ðə ˈfʊtbɔːl wɪð hɪz lɛft fʊt/",
    hint: "The part of the body at the bottom of the leg. 🦶",
  },
  {
    id: 133,
    displaySentence: "She has beautiful blue ___ like her mother.",
    fullSentence: "She has beautiful blue eyes like her mother.",
    answer: "eyes",
    options: ["ears", "eyes", "lips", "hands"],
    translation: "Cô ấy có đôi mắt xanh tuyệt đẹp giống mẹ mình.",
    ipa: "/ʃiː hæz ˈbjuːtɪfʊl bluː aɪz laɪk hɜː ˈmʌðə/",
    hint: "You use them to see. 👀",
  },
  {
    id: 134,
    displaySentence: "My grandfather cannot hear well with his left ___.",
    fullSentence: "My grandfather cannot hear well with his left ear.",
    answer: "ear",
    options: ["eye", "nose", "ear", "mouth"],
    translation: "Ông của tôi không thể nghe rõ bằng tai trái.",
    ipa: "/maɪ ˈɡrændˌfɑːðə ˈkænɒt hɪə wɛl wɪð hɪz lɛft ɪə/",
    hint: "You use it to hear sounds. 👂",
  },
  {
    id: 135,
    displaySentence: "Pinocchio is famous for having a long ___.",
    fullSentence: "Pinocchio is famous for having a long nose.",
    answer: "nose",
    options: ["arm", "leg", "nose", "neck"],
    translation: "Pinocchio nổi tiếng với chiếc mũi dài.",
    ipa: "/pɪˈnəʊkɪəʊ ɪz ˈfeɪməs fɔː ˈhævɪŋ ə lɒŋ nəʊz/",
    hint: "You use it to smell. 👃",
  },
  {
    id: 136,
    displaySentence: "Please open your ___ wide for the dentist.",
    fullSentence: "Please open your mouth wide for the dentist.",
    answer: "mouth",
    options: ["mouth", "eye", "ear", "hand"],
    translation: "Vui lòng mở to miệng cho nha sĩ khám.",
    ipa: "/pliːz ˈəʊpən jɔː maʊθ waɪd fɔː ðə ˈdɛntɪst/",
    hint: "You use it to eat and speak. 👄",
  },
  {
    id: 137,
    displaySentence: "She went to the salon to cut her long black ___.",
    fullSentence: "She went to the salon to cut her long black hair.",
    answer: "hair",
    options: ["nail", "hair", "skin", "dress"],
    translation: "Cô ấy đã đến tiệm để cắt mái tóc đen dài của mình.",
    ipa: "/ʃiː wɛnt tuː ðə ˈsælɒn tuː kʌt hɜː lɒŋ blæk heə/",
    hint: "It grows on top of your head. 💇",
  },
  {
    id: 138,
    displaySentence: "He broke his ___ while skiing in the mountains.",
    fullSentence: "He broke his leg while skiing in the mountains.",
    answer: "leg",
    options: ["arm", "leg", "nose", "finger"],
    translation: "Anh ấy đã bị gãy chân khi trượt tuyết trên núi.",
    ipa: "/hiː brəʊk hɪz lɛɡ waɪl ˈskiːɪŋ ɪn ðə ˈmaʊntɪnz/",
    hint: "You use it to walk and run. 🦵",
  },
  {
    id: 139,
    displaySentence: "She is carrying a heavy box under her right ___.",
    fullSentence: "She is carrying a heavy box under her right arm.",
    answer: "arm",
    options: ["leg", "arm", "eye", "foot"],
    translation: "Cô ấy đang kẹp một cái hộp nặng dưới cánh tay phải.",
    ipa: "/ʃiː ɪz ˈkæriɪŋ ə ˈhɛvi bɒks ˈʌndə hɜː raɪt ɑːm/",
    hint: "The upper limb from shoulder to hand. 💪",
  },
  {
    id: 140,
    displaySentence: "I have a bad ache in my ___ today.",
    fullSentence: "I have a bad ache in my head today.",
    answer: "head",
    options: ["head", "shoe", "bag", "chair"],
    translation: "Hôm nay tôi bị đau đầu dữ dội.",
    ipa: "/aɪ hæv ə bæd eɪk ɪn maɪ hɛd təˈdeɪ/",
    hint: "Contains your brain. 🤕",
  },
  {
    id: 141,
    displaySentence: "My ___ is my father's father.",
    fullSentence: "My grandfather is my father's father.",
    answer: "grandfather",
    options: ["uncle", "grandfather", "brother", "son"],
    translation: "Ông nội tôi là cha của cha tôi.",
    ipa: "/maɪ ˈɡrændˌfɑːðər ɪz maɪ ˈfɑːðəz ˈfɑːðə/",
    hint: "An old man in the family. 👴",
  },
  {
    id: 142,
    displaySentence: "My ___ bakes the best cookies in the world.",
    fullSentence: "My grandmother bakes the best cookies in the world.",
    answer: "grandmother",
    options: ["grandmother", "sister", "aunt", "daughter"],
    translation: "Bà của tôi nướng bánh quy ngon nhất thế giới.",
    ipa: "/maɪ ˈɡrænˌmʌðə beɪks ðə bɛst ˈkʊkiz ɪn ðə wɜːld/",
    hint: "An old woman in the family. 👵",
  },
  {
    id: 143,
    displaySentence: "My older ___ taught me how to ride a bike.",
    fullSentence: "My older brother taught me how to ride a bike.",
    answer: "brother",
    options: ["sister", "uncle", "brother", "aunt"],
    translation: "Anh trai tôi đã dạy tôi cách đi xe đạp.",
    ipa: "/maɪ ˈəʊldə ˈbrʌðə tɔːt miː haʊ tuː raɪd ə baɪk/",
    hint: "A male sibling. 👦",
  },
  {
    id: 144,
    displaySentence: "I share a bedroom with my younger ___.",
    fullSentence: "I share a bedroom with my younger sister.",
    answer: "sister",
    options: ["brother", "father", "uncle", "sister"],
    translation: "Tôi chung phòng ngủ với em gái mình.",
    ipa: "/aɪ ʃeər ə ˈbɛdru(ː)m wɪð maɪ ˈjʌŋɡə ˈsɪstə/",
    hint: "A female sibling. 👧",
  },
  {
    id: 145,
    displaySentence: "The cute ___ is sleeping peacefully in the crib.",
    fullSentence: "The cute baby is sleeping peacefully in the crib.",
    answer: "baby",
    options: ["adult", "man", "baby", "teenager"],
    translation: "Đứa bé đáng yêu đang ngủ yên bình trong nôi.",
    ipa: "/ðə kjuːt ˈbeɪbi ɪz ˈsliːpɪŋ ˈpiːsfʊli ɪn ðə krɪb/",
    hint: "A very young child. 👶",
  },
  {
    id: 146,
    displaySentence: "The little ___ is playing with his toy cars.",
    fullSentence: "The little boy is playing with his toy cars.",
    answer: "boy",
    options: ["girl", "woman", "boy", "aunt"],
    translation: "Cậu bé đang chơi với những chiếc ô tô đồ chơi của mình.",
    ipa: "/ðə ˈlɪtl bɔɪ ɪz ˈpleɪɪŋ wɪð hɪz tɔɪ kɑːz/",
    hint: "A male child. 👦",
  },
  {
    id: 147,
    displaySentence: "The young ___ is reading a fairy tale book.",
    fullSentence: "The young girl is reading a fairy tale book.",
    answer: "girl",
    options: ["boy", "man", "uncle", "girl"],
    translation: "Cô bé đang đọc một cuốn sách truyện cổ tích.",
    ipa: "/ðə jʌŋ ɡɜːl ɪz ˈriːdɪŋ ə ˈfeəri teɪl bʊk/",
    hint: "A female child. 👧",
  },
  {
    id: 148,
    displaySentence: "That tall ___ is wearing a black suit and tie.",
    fullSentence: "That tall man is wearing a black suit and tie.",
    answer: "man",
    options: ["woman", "man", "girl", "child"],
    translation:
      "Người đàn ông cao lớn đó đang mặc một bộ vest đen và đeo cà vạt.",
    ipa: "/ðæt tɔːl mæn ɪz ˈweərɪŋ ə blæk sjuːt ænd taɪ/",
    hint: "An adult male. 👨",
  },
  {
    id: 149,
    displaySentence: "The elegant ___ walked into the room with confidence.",
    fullSentence: "The elegant woman walked into the room with confidence.",
    answer: "woman",
    options: ["man", "boy", "woman", "dog"],
    translation: "Người phụ nữ thanh lịch tự tin bước vào phòng.",
    ipa: "/ði ˈɛlɪɡənt ˈwʊmən wɔːkt ˈɪntʊ ðə ruːm wɪð ˈkɒnfɪdəns/",
    hint: "An adult female. 👩",
  },
  {
    id: 150,
    displaySentence: "Every ___ deserves a good education.",
    fullSentence: "Every child deserves a good education.",
    answer: "child",
    options: ["child", "adult", "animal", "plant"],
    translation: "Mọi trẻ em đều xứng đáng có một nền giáo dục tốt.",
    ipa: "/ˈɛvri tʃaɪld dɪˈzɜːvz ə ɡʊd ˌɛdju(ː)ˈkeɪʃən/",
    hint: "A young human being. 🧒",
  },
  {
    id: 151,
    displaySentence: "Stop your car when the traffic light turns ___.",
    fullSentence: "Stop your car when the traffic light turns red.",
    answer: "red",
    options: ["green", "yellow", "red", "blue"],
    translation: "Dừng xe khi đèn giao thông chuyển sang màu đỏ.",
    ipa: "/stɒp jɔː kɑː wɛn ðə ˈtræfɪk laɪt tɜːnz rɛd/",
    hint: "The color of an apple or blood. 🔴",
  },
  {
    id: 152,
    displaySentence: "The sky is so clear and ___ today.",
    fullSentence: "The sky is so clear and blue today.",
    answer: "blue",
    options: ["red", "blue", "green", "black"],
    translation: "Bầu trời hôm nay thật trong trẻo và xanh biếc.",
    ipa: "/ðə skaɪ ɪz səʊ klɪə ænd bluː təˈdeɪ/",
    hint: "The color of the ocean. 🔵",
  },
  {
    id: 153,
    displaySentence: "The frogs in the pond are completely ___.",
    fullSentence: "The frogs in the pond are completely green.",
    answer: "green",
    options: ["purple", "yellow", "green", "pink"],
    translation: "Những con ếch trong ao hoàn toàn có màu xanh lá cây.",
    ipa: "/ðə frɒɡz ɪn ðə pɒnd ɑː kəmˈpliːtli ɡriːn/",
    hint: "The color of grass and leaves. 🟢",
  },
  {
    id: 154,
    displaySentence: "Bananas and lemons are usually ___.",
    fullSentence: "Bananas and lemons are usually yellow.",
    answer: "yellow",
    options: ["red", "yellow", "black", "white"],
    translation: "Chuối và chanh thường có màu vàng.",
    ipa: "/bəˈnɑːnəz ænd ˈlɛmənz ɑː ˈjuːʒuəli ˈjɛləʊ/",
    hint: "The color of the sun. 🟡",
  },
  {
    id: 155,
    displaySentence: "He wore a stylish ___ leather jacket to the concert.",
    fullSentence: "He wore a stylish black leather jacket to the concert.",
    answer: "black",
    options: ["white", "black", "yellow", "orange"],
    translation:
      "Anh ấy đã mặc một chiếc áo khoác da màu đen sành điệu đến buổi hòa nhạc.",
    ipa: "/hiː wɔːr ə ˈstaɪlɪʃ blæk ˈlɛðə ˈdʒækɪt tuː ðə ˈkɒnsət/",
    hint: "The color of the night sky. ⚫",
  },
  {
    id: 156,
    displaySentence: "The bride looked gorgeous in her ___ wedding dress.",
    fullSentence: "The bride looked gorgeous in her white wedding dress.",
    answer: "white",
    options: ["red", "black", "white", "green"],
    translation: "Cô dâu trông thật lộng lẫy trong chiếc váy cưới màu trắng.",
    ipa: "/ðə braɪd lʊkt ˈɡɔːdʒəs ɪn hɜː waɪt ˈwɛdɪŋ drɛs/",
    hint: "The color of snow and milk. ⚪",
  },
  {
    id: 157,
    displaySentence: "Most tree trunks are covered in ___ bark.",
    fullSentence: "Most tree trunks are covered in brown bark.",
    answer: "brown",
    options: ["brown", "blue", "pink", "purple"],
    translation: "Hầu hết các thân cây đều được bao phủ bởi lớp vỏ màu nâu.",
    ipa: "/məʊst triː trʌŋks ɑː ˈkʌvəd ɪn braʊn bɑːk/",
    hint: "The color of chocolate and dirt. 🟤",
  },
  {
    id: 158,
    displaySentence: "Carrots and pumpkins are bright ___.",
    fullSentence: "Carrots and pumpkins are bright orange.",
    answer: "orange",
    options: ["purple", "orange", "grey", "white"],
    translation: "Cà rốt và bí ngô có màu cam tươi.",
    ipa: "/ˈkærəts ænd ˈpʌmpkɪnz ɑː braɪt ˈɒrɪndʒ/",
    hint: "A mix of red and yellow. 🟠",
  },
  {
    id: 159,
    displaySentence: "Flamingos are known for their beautiful ___ feathers.",
    fullSentence: "Flamingos are known for their beautiful pink feathers.",
    answer: "pink",
    options: ["pink", "black", "blue", "green"],
    translation: "Hồng hạc được biết đến với bộ lông màu hồng tuyệt đẹp.",
    ipa: "/fləˈmɪŋɡəʊz ɑː nəʊn fɔː ðeə ˈbjuːtɪfʊl pɪŋk ˈfɛðəz/",
    hint: "A pale red color. 🌸",
  },
  {
    id: 160,
    displaySentence: "Grapes and eggplants are often dark ___.",
    fullSentence: "Grapes and eggplants are often dark purple.",
    answer: "purple",
    options: ["yellow", "white", "purple", "orange"],
    translation: "Nho và cà tím thường có màu tím sẫm.",
    ipa: "/ɡreɪps ænd ˈɛɡplɑːnts ɑːr ˈɒf(ə)n dɑːk ˈpɜːpl/",
    hint: "A mix of red and blue. 🟣",
  },
  {
    id: 161,
    displaySentence: "My father drives his ___ to work every day.",
    fullSentence: "My father drives his car to work every day.",
    answer: "car",
    options: ["plane", "boat", "car", "train"],
    translation: "Bố tôi lái ô tô đi làm mỗi ngày.",
    ipa: "/maɪ ˈfɑːðə draɪvz hɪz kɑː tuː wɜːk ˈɛvri deɪ/",
    hint: "A four-wheeled road vehicle. 🚗",
  },
  {
    id: 162,
    displaySentence: "We rented a small wooden ___ to row across the lake.",
    fullSentence: "We rented a small wooden boat to row across the lake.",
    answer: "boat",
    options: ["car", "bus", "train", "boat"],
    translation: "Chúng tôi đã thuê một chiếc thuyền gỗ nhỏ để chèo qua hồ.",
    ipa: "/wiː ˈrɛntɪd ə smɔːl ˈwʊdn bəʊt tuː rəʊ əˈkrɒs ðə leɪk/",
    hint: "A small vessel for travelling on water. 🛶",
  },
  {
    id: 163,
    displaySentence: "The cruise ___ sailed across the Atlantic Ocean.",
    fullSentence: "The cruise ship sailed across the Atlantic Ocean.",
    answer: "ship",
    options: ["ship", "car", "bike", "bus"],
    translation: "Tàu du lịch đã ra khơi băng qua Đại Tây Dương.",
    ipa: "/ðə kruːz ʃɪp seɪld əˈkrɒs ði ətˈlæntɪk ˈəʊʃən/",
    hint: "A large boat for transporting people or goods by sea. 🚢",
  },
  {
    id: 164,
    displaySentence: "The ___ rescued the people from the mountain top.",
    fullSentence: "The helicopter rescued the people from the mountain top.",
    answer: "helicopter",
    options: ["car", "train", "helicopter", "bicycle"],
    translation: "Trực thăng đã giải cứu những người từ đỉnh núi.",
    ipa: "/ðə ˈhɛlɪkɒptə ˈrɛskjuːd ðə ˈpiːpl frɒm ðə ˈmaʊntɪn tɒp/",
    hint: "An aircraft with spinning blades on top. 🚁",
  },
  {
    id: 165,
    displaySentence: "He loves riding his fast ___ on the open highway.",
    fullSentence: "He loves riding his fast motorcycle on the open highway.",
    answer: "motorcycle",
    options: ["train", "plane", "motorcycle", "ship"],
    translation:
      "Anh ấy thích lái chiếc xe máy nhanh của mình trên đường cao tốc thênh thang.",
    ipa: "/hiː lʌvz ˈraɪdɪŋ hɪz fɑːst ˈməʊtəˌsaɪkl ɒn ði ˈəʊpən ˈhaɪweɪ/",
    hint: "A two-wheeled vehicle with an engine. 🏍️",
  },
  {
    id: 166,
    displaySentence: "Please look both ways before you cross the ___.",
    fullSentence: "Please look both ways before you cross the street.",
    answer: "street",
    options: ["street", "river", "mountain", "sky"],
    translation: "Vui lòng nhìn cả hai hướng trước khi bạn băng qua đường.",
    ipa: "/pliːz lʊk bəʊθ weɪz bɪˈfɔː juː krɒs ðə striːt/",
    hint: "A public road in a city or town. 🛣️",
  },
  {
    id: 167,
    displaySentence: "New York is a very busy and crowded ___.",
    fullSentence: "New York is a very busy and crowded city.",
    answer: "city",
    options: ["village", "farm", "forest", "city"],
    translation: "New York là một thành phố rất nhộn nhịp và đông đúc.",
    ipa: "/njuː jɔːk ɪz ə ˈvɛri ˈbɪzi ænd ˈkraʊdɪd ˈsɪti/",
    hint: "A large and important town. 🏙️",
  },
  {
    id: 168,
    displaySentence: "She grew up in a quiet little ___ by the sea.",
    fullSentence: "She grew up in a quiet little town by the sea.",
    answer: "town",
    options: ["town", "country", "planet", "galaxy"],
    translation: "Cô ấy lớn lên ở một thị trấn nhỏ yên tĩnh bên bờ biển.",
    ipa: "/ʃiː ɡruː ʌp ɪn ə ˈkwaɪɪt ˈlɪtl taʊn baɪ ðə siː/",
    hint: "Larger than a village but smaller than a city. 🏘️",
  },
  {
    id: 169,
    displaySentence: "The farmers live in a small rural ___.",
    fullSentence: "The farmers live in a small rural village.",
    answer: "village",
    options: ["village", "city", "capital", "ocean"],
    translation:
      "Những người nông dân sống trong một ngôi làng nhỏ ở nông thôn.",
    ipa: "/ðə ˈfɑːməz lɪv ɪn ə smɔːl ˈrʊərəl ˈvɪlɪdʒ/",
    hint: "A group of houses situated in a rural area. 🏡",
  },
  {
    id: 170,
    displaySentence: "Japan is a beautiful ___ in East Asia.",
    fullSentence: "Japan is a beautiful country in East Asia.",
    answer: "country",
    options: ["city", "town", "country", "village"],
    translation: "Nhật Bản là một quốc gia xinh đẹp ở Đông Á.",
    ipa: "/dʒəˈpæn ɪz ə ˈbjuːtɪfʊl ˈkʌntri ɪn iːst ˈeɪʒə/",
    hint: "A nation with its own government. 🇯🇵",
  },
  {
    id: 171,
    displaySentence: "It is chilly outside, you should wear a ___.",
    fullSentence: "It is chilly outside, you should wear a jacket.",
    answer: "jacket",
    options: ["skirt", "jacket", "shoe", "sock"],
    translation: "Bên ngoài trời se lạnh, bạn nên mặc một chiếc áo khoác.",
    ipa: "/ɪt ɪz ˈtʃɪli ˌaʊtˈsaɪd, juː ʃʊd weər ə ˈdʒækɪt/",
    hint: "A short coat. 🧥",
  },
  {
    id: 172,
    displaySentence: "He wore a heavy winter ___ when it snowed.",
    fullSentence: "He wore a heavy winter coat when it snowed.",
    answer: "coat",
    options: ["coat", "t-shirt", "belt", "ring"],
    translation:
      "Anh ấy đã mặc một chiếc áo khoác mùa đông dày khi trời có tuyết.",
    ipa: "/hiː wɔːr ə ˈhɛvi ˈwɪntə kəʊt wɛn ɪt snəʊd/",
    hint: "A long piece of clothing worn outdoors for warmth. 🧥",
  },
  {
    id: 173,
    displaySentence: "The school uniform for girls includes a plaid ___.",
    fullSentence: "The school uniform for girls includes a plaid skirt.",
    answer: "skirt",
    options: ["shirt", "skirt", "hat", "sock"],
    translation:
      "Đồng phục học sinh dành cho nữ sinh bao gồm một chiếc váy kẻ sọc.",
    ipa: "/ðə skuːl ˈjuːnɪfɔːm fɔː ɡɜːlz ɪnˈkluːdz ə plæd skɜːt/",
    hint: "A woman's garment that hangs from the waist. 👗",
  },
  {
    id: 174,
    displaySentence: "He was wearing a casual white ___ and blue jeans.",
    fullSentence: "He was wearing a casual white T-shirt and blue jeans.",
    answer: "T-shirt",
    options: ["T-shirt", "shoe", "belt", "watch"],
    translation:
      "Anh ấy đang mặc một chiếc áo thun trắng giản dị và quần jean xanh.",
    ipa: "/hiː wɒz ˈweərɪŋ ə ˈkæʒʊəl waɪt ˈtiːˌʃɜːt ænd bluː dʒiːnz/",
    hint: "A short-sleeved casual top. 👕",
  },
  {
    id: 175,
    displaySentence: "I need a clean pair of ___ to wear with my sneakers.",
    fullSentence: "I need a clean pair of socks to wear with my sneakers.",
    answer: "socks",
    options: ["gloves", "glasses", "socks", "pants"],
    translation:
      "Tôi cần một đôi tất sạch để đi cùng với đôi giày thể thao của mình.",
    ipa: "/aɪ niːd ə kliːn peər əv sɒks tuː weə wɪð maɪ ˈsniːkəz/",
    hint: "You wear them on your feet inside shoes. 🧦",
  },
  {
    id: 176,
    displaySentence: "I usually wake up at 6 AM in the ___.",
    fullSentence: "I usually wake up at 6 AM in the morning.",
    answer: "morning",
    options: ["morning", "afternoon", "evening", "night"],
    translation: "Tôi thường thức dậy lúc 6 giờ sáng.",
    ipa: "/aɪ ˈjuːʒuəli weɪk ʌp æt 6 eɪ-ɛm ɪn ðə ˈmɔːnɪŋ/",
    hint: "The early part of the day. 🌅",
  },
  {
    id: 177,
    displaySentence: "We have our English class in the ___, after lunch.",
    fullSentence: "We have our English class in the afternoon, after lunch.",
    answer: "afternoon",
    options: ["morning", "afternoon", "night", "week"],
    translation:
      "Chúng tôi có tiết học tiếng Anh vào buổi chiều, sau bữa trưa.",
    ipa: "/wiː hæv ˈaʊər ˈɪŋɡlɪʃ klɑːs ɪn ði ˌɑːftəˈnuːn, ˈɑːftə lʌntʃ/",
    hint: "The time between noon and evening. ☀️",
  },
  {
    id: 178,
    displaySentence: "They always watch a movie together in the ___.",
    fullSentence: "They always watch a movie together in the evening.",
    answer: "evening",
    options: ["evening", "morning", "noon", "year"],
    translation: "Họ luôn xem phim cùng nhau vào buổi tối.",
    ipa: "/ðeɪ ˈɔːlweɪz wɒtʃ ə ˈmuːvi təˈɡɛðər ɪn ði ˈiːvnɪŋ/",
    hint: "The part of the day between late afternoon and night. 🌇",
  },
  {
    id: 179,
    displaySentence: "The stars are very bright tonight in the dark ___.",
    fullSentence: "The stars are very bright tonight in the dark night.",
    answer: "night",
    options: ["day", "morning", "night", "afternoon"],
    translation: "Những vì sao đêm nay rất sáng trong màn đêm tăm tối.",
    ipa: "/ðə stɑːz ɑː ˈvɛri braɪt təˈnaɪt ɪn ðə dɑːk naɪt/",
    hint: "When you go to sleep. 🌙",
  },
  {
    id: 180,
    displaySentence: "There are seven days in a ___, starting with Monday.",
    fullSentence: "There are seven days in a week, starting with Monday.",
    answer: "week",
    options: ["month", "year", "week", "decade"],
    translation: "Có bảy ngày trong một tuần, bắt đầu bằng thứ Hai.",
    ipa: "/ðeər ɑː ˈsɛvn deɪz ɪn ə wiːk, ˈstɑːtɪŋ wɪð ˈmʌndeɪ/",
    hint: "Monday to Sunday. 📅",
  },
];
