const vocabularies = [
  // 5 câu hỏi gốc
  {
    image: "https://images.unsplash.com/photo-1579613832125-5d34a13ffe2a?w=800",
    options: ["Banana", "Apple", "Orange", "Grape"],
    correctAnswer: "Apple",
    partOfSpeech: "noun",
    ipa: "/ˈæp.əl/",
    explanation:
      "Một loại trái cây tròn, vỏ màu xanh hoặc đỏ, thịt quả giòn và có vị ngọt.",
    example: "She eats an apple every morning to stay healthy.",
  },
  {
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
    options: ["Bicycle", "Bus", "Car", "Motorbike"],
    correctAnswer: "Car",
    partOfSpeech: "noun",
    ipa: "/kɑːr/",
    explanation:
      "Một phương tiện giao thông đường bộ có bốn bánh, chạy bằng động cơ.",
    example: "They decided to travel by car to the countryside.",
  },
  {
    image: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800",
    options: ["Cat", "Dog", "Lion", "Tiger"],
    correctAnswer: "Dog",
    partOfSpeech: "noun",
    ipa: "/dɒɡ/",
    explanation:
      "Một loài động vật được thuần hóa, thường được nuôi làm thú cưng hoặc để giữ nhà.",
    example: "The dog wagged its tail happily when its owner came home.",
  },
  {
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800",
    options: ["Newspaper", "Magazine", "Book", "Notebook"],
    correctAnswer: "Book",
    partOfSpeech: "noun",
    ipa: "/bʊk/",
    explanation:
      "Một tập hợp các trang giấy in hoặc viết có chữ, được đóng lại với nhau.",
    example: "I am reading a fascinating book about ancient history.",
  },
  {
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
    options: ["Pizza", "Burger", "Salad", "Pasta"],
    correctAnswer: "Pizza",
    partOfSpeech: "noun",
    ipa: "/ˈpiːt.sə/",
    explanation:
      "Một món ăn Ý có đế bánh mì dẹt, tròn, phủ sốt cà chua, phô mai và các loại nhân khác.",
    example: "Let's order a large pizza for the party tonight.",
  },

  // Động vật
  {
    image: "https://images.unsplash.com/photo-1518791841217-8f162f1e1131?w=800",
    options: ["Dog", "Cat", "Bird", "Fish"],
    correctAnswer: "Cat",
    partOfSpeech: "noun",
    ipa: "/kæt/",
    explanation:
      "Một loài động vật có vú nhỏ, có lông mềm, đuôi dài, thường được nuôi làm thú cưng.",
    example: "The cat is sleeping peacefully on the sofa.",
  },
  {
    image: "https://images.unsplash.com/photo-1555169062-013468b47731?w=800",
    options: ["Horse", "Cow", "Sheep", "Goat"],
    correctAnswer: "Horse",
    partOfSpeech: "noun",
    ipa: "/hɔːs/",
    explanation:
      "Một loài động vật bốn chân to lớn, được dùng để cưỡi hoặc kéo xe.",
    example: "She learned to ride a horse when she was a child.",
  },
  {
    image: "https://images.unsplash.com/photo-1437622368342-7a3d73a34c8f?w=800",
    options: ["Shark", "Dolphin", "Whale", "Turtle"],
    correctAnswer: "Turtle",
    partOfSpeech: "noun",
    ipa: "/ˈtɜː.təl/",
    explanation:
      "Một loài bò sát sống ở biển hoặc đất liền, có mai cứng để bảo vệ cơ thể.",
    example: "The sea turtle slowly made its way to the ocean.",
  },
  {
    image: "https://images.unsplash.com/photo-1598755257130-c4d1284319a2?w=800",
    options: ["Elephant", "Lion", "Giraffe", "Zebra"],
    correctAnswer: "Elephant",
    partOfSpeech: "noun",
    ipa: "/ˈel.ɪ.fənt/",
    explanation: "Động vật có vú lớn nhất trên cạn, có vòi dài và ngà.",
    example: "An elephant can drink up to 200 liters of water a day.",
  },
  {
    image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800",
    options: ["Panda", "Koala", "Bear", "Monkey"],
    correctAnswer: "Panda",
    partOfSpeech: "noun",
    ipa: "/ˈpæn.də/",
    explanation: "Một loài gấu lớn màu đen trắng, sống ở Trung Quốc và ăn tre.",
    example: "The giant panda is a symbol of wildlife conservation.",
  },
  {
    image: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800",
    options: ["Wolf", "Fox", "Bear", "Deer"],
    correctAnswer: "Fox",
    partOfSpeech: "noun",
    ipa: "/fɒks/",
    explanation:
      "Một loài động vật hoang dã thuộc họ chó, có đuôi rậm và mõm nhọn.",
    example: "A cunning fox slipped into the chicken coop.",
  },
  {
    image: "https://images.unsplash.com/photo-1534568288833-913a0b06b6e4?w=800",
    options: ["Fish", "Crab", "Octopus", "Jellyfish"],
    correctAnswer: "Fish",
    partOfSpeech: "noun",
    ipa: "/fɪʃ/",
    explanation: "Động vật sống dưới nước, có vây và thở bằng mang.",
    example: "He caught a big fish in the lake yesterday.",
  },
  {
    image: "https://images.unsplash.com/photo-1497206365907-f5e630693df0?w=800",
    options: ["Parrot", "Eagle", "Owl", "Penguin"],
    correctAnswer: "Owl",
    partOfSpeech: "noun",
    ipa: "/aʊl/",
    explanation:
      "Một loài chim săn mồi ban đêm với đôi mắt to và khả năng quay đầu rộng.",
    example: "We heard the hoot of an owl late at night.",
  },
  {
    image: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800",
    options: ["Puppy", "Kitten", "Cub", "Fawn"],
    correctAnswer: "Puppy",
    partOfSpeech: "noun",
    ipa: "/ˈpʌp.i/",
    explanation: "Một con chó con.",
    example: "My sister adopted an adorable puppy from the shelter.",
  },
  {
    image: "https://images.unsplash.com/photo-1589922582845-3978936274ca?w=800",
    options: ["Snake", "Lizard", "Crocodile", "Frog"],
    correctAnswer: "Frog",
    partOfSpeech: "noun",
    ipa: "/frɒɡ/",
    explanation:
      "Một loài lưỡng cư nhỏ, không đuôi, có da trơn và chân sau dài để nhảy.",
    example: "A green frog jumped into the pond.",
  },

  // Trái cây & Rau củ
  {
    image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?w=800",
    options: ["Apple", "Banana", "Cherry", "Date"],
    correctAnswer: "Banana",
    partOfSpeech: "noun",
    ipa: "/bəˈnɑː.nə/",
    explanation: "Một loại trái cây dài, cong, có vỏ màu vàng khi chín.",
    example: "Monkeys love to eat bananas.",
  },
  {
    image: "https://images.unsplash.com/photo-1587393855524-087f83d95c9f?w=800",
    options: ["Grape", "Strawberry", "Blueberry", "Raspberry"],
    correctAnswer: "Strawberry",
    partOfSpeech: "noun",
    ipa: "/ˈstrɔː.bər.i/",
    explanation: "Một loại quả mọng nhỏ màu đỏ, có vị ngọt và thơm.",
    example: "We went to a farm to pick fresh strawberries.",
  },
  {
    image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=800",
    options: ["Pineapple", "Mango", "Papaya", "Kiwi"],
    correctAnswer: "Pineapple",
    partOfSpeech: "noun",
    ipa: "/ˈpaɪn.æp.əl/",
    explanation:
      "Một loại trái cây nhiệt đới lớn, có vỏ cứng, xù xì và thịt quả màu vàng, vị ngọt.",
    example: "Pineapple juice is very refreshing on a hot day.",
  },
  {
    image: "https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=800",
    options: ["Watermelon", "Cantaloupe", "Honeydew", "Melon"],
    correctAnswer: "Watermelon",
    partOfSpeech: "noun",
    ipa: "/ˈwɔː.təˌmel.ən/",
    explanation:
      "Một loại quả lớn, tròn hoặc bầu dục, vỏ xanh, ruột đỏ và nhiều nước.",
    example: "Eating cold watermelon is perfect for a summer day.",
  },
  {
    image: "https://images.unsplash.com/photo-1582571862217-33744e5f483c?w=800",
    options: ["Lemon", "Lime", "Orange", "Grapefruit"],
    correctAnswer: "Orange",
    partOfSpeech: "noun",
    ipa: "/ˈɒr.ɪndʒ/",
    explanation:
      "Một loại trái cây có múi, hình tròn, màu cam, có vị ngọt và chua.",
    example: "She squeezed an orange to make fresh juice.",
  },
  {
    image: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800",
    options: ["Carrot", "Potato", "Onion", "Garlic"],
    correctAnswer: "Carrot",
    partOfSpeech: "noun",
    ipa: "/ˈkær.ət/",
    explanation: "Một loại củ rễ màu cam, thường được dùng làm rau.",
    example: "Rabbits are known for loving carrots.",
  },
  {
    image: "https://images.unsplash.com/photo-1570586922256-427c1332f399?w=800",
    options: ["Broccoli", "Cauliflower", "Cabbage", "Lettuce"],
    correctAnswer: "Broccoli",
    partOfSpeech: "noun",
    ipa: "/ˈbrɒk.əl.i/",
    explanation:
      "Một loại rau có hoa màu xanh đậm, trông giống như một cái cây nhỏ.",
    example: "Broccoli is a very nutritious vegetable.",
  },
  {
    image: "https://images.unsplash.com/photo-1597362925123-518d3d5ac979?w=800",
    options: ["Corn", "Pea", "Bean", "Asparagus"],
    correctAnswer: "Corn",
    partOfSpeech: "noun",
    ipa: "/kɔːn/",
    explanation:
      "Một loại ngũ cốc có hạt lớn mọc trên lõi, thường có màu vàng.",
    example: "We had corn on the cob at the barbecue.",
  },
  {
    image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800",
    options: ["Mushroom", "Pepper", "Eggplant", "Potato"],
    correctAnswer: "Potato",
    partOfSpeech: "noun",
    ipa: "/pəˈteɪ.təʊ/",
    explanation: "Một loại củ ăn được, có nhiều tinh bột, vỏ mỏng và ruột đặc.",
    example: "French fries are made from potatoes.",
  },
  {
    image: "https://images.unsplash.com/photo-1601648764329-19543c798b2c?w=800",
    options: ["Tomato", "Cucumber", "Zucchini", "Pumpkin"],
    correctAnswer: "Tomato",
    partOfSpeech: "noun",
    ipa: "/təˈmɑː.təʊ/",
    explanation:
      "Một loại quả mọng, màu đỏ, thường được dùng như một loại rau trong nấu ăn.",
    example: "A fresh tomato is a key ingredient in many salads.",
  },

  // Thiên nhiên
  {
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800",
    options: ["Mountain", "River", "Forest", "Desert"],
    correctAnswer: "River",
    partOfSpeech: "noun",
    ipa: "/ˈrɪv.ər/",
    explanation:
      "Một dòng nước tự nhiên lớn chảy ra biển, hồ hoặc một con sông khác.",
    example: "The city was built on the banks of a large river.",
  },
  {
    image: "https://images.unsplash.com/photo-1454789548928-9efd52dc4031?w=800",
    options: ["Sun", "Moon", "Star", "Cloud"],
    correctAnswer: "Moon",
    partOfSpeech: "noun",
    ipa: "/muːn/",
    explanation:
      "Thiên thể quay quanh Trái Đất và có thể nhìn thấy vào ban đêm.",
    example: "The full moon looks beautiful tonight.",
  },
  {
    image: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=800",
    options: ["Rain", "Snow", "Wind", "Fog"],
    correctAnswer: "Rain",
    partOfSpeech: "noun",
    ipa: "/reɪn/",
    explanation: "Nước rơi xuống từ các đám mây dưới dạng giọt.",
    example: "Don't forget your umbrella, it looks like rain.",
  },
  {
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800",
    options: ["Lake", "Ocean", "Pond", "Waterfall"],
    correctAnswer: "Lake",
    partOfSpeech: "noun",
    ipa: "/leɪk/",
    explanation: "Một vùng nước ngọt lớn được đất liền bao quanh.",
    example: "They went for a swim in the lake.",
  },
  {
    image: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=800",
    options: ["Jungle", "Forest", "Wood", "Grove"],
    correctAnswer: "Forest",
    partOfSpeech: "noun",
    ipa: "/ˈfɒr.ɪst/",
    explanation:
      "Một khu vực rộng lớn được bao phủ bởi cây cối và thảm thực vật.",
    example: "We went for a long walk in the forest.",
  },
  {
    image: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=800",
    options: ["Sunrise", "Sunset", "Dawn", "Dusk"],
    correctAnswer: "Sunrise",
    partOfSpeech: "noun",
    ipa: "/ˈsʌn.raɪz/",
    explanation: "Thời điểm vào buổi sáng khi mặt trời bắt đầu xuất hiện.",
    example: "Waking up early to watch the sunrise is a wonderful experience.",
  },
  {
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800",
    options: ["Rose", "Tulip", "Daisy", "Flower"],
    correctAnswer: "Flower",
    partOfSpeech: "noun",
    ipa: "/ˈflaʊ.ər/",
    explanation: "Bộ phận có màu sắc của cây, nơi tạo ra hạt hoặc quả.",
    example: "He gave her a beautiful flower.",
  },
  {
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    options: ["Tree", "Bush", "Grass", "Leaf"],
    correctAnswer: "Tree",
    partOfSpeech: "noun",
    ipa: "/triː/",
    explanation: "Một loài thực vật cao, có thân gỗ và cành lá.",
    example: "That old oak tree has been here for centuries.",
  },
  {
    image: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=800",
    options: ["Plant", "Root", "Stem", "Branch"],
    correctAnswer: "Plant",
    partOfSpeech: "noun",
    ipa: "/plɑːnt/",
    explanation:
      "Một sinh vật sống, chẳng hạn như cây, cỏ, không phải là động vật.",
    example: "She has many beautiful plants in her garden.",
  },
  {
    image: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=800",
    options: ["Path", "Road", "Street", "Avenue"],
    correctAnswer: "Path",
    partOfSpeech: "noun",
    ipa: "/pɑːθ/",
    explanation:
      "Một con đường hoặc lối đi được tạo ra trên mặt đất bởi người đi bộ.",
    example: "Follow this path through the woods.",
  },

  // Đồ vật
  {
    image: "https://images.unsplash.com/photo-1511556532299-8f662fc26c06?w=800",
    options: ["Shoe", "Boot", "Sandal", "Slipper"],
    correctAnswer: "Shoe",
    partOfSpeech: "noun",
    ipa: "/ʃuː/",
    explanation: "Một vật dụng để mang ở chân, thường làm bằng da hoặc vải.",
    example: "I need to buy a new pair of shoes.",
  },
  {
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800",
    options: ["Clock", "Watch", "Timer", "Alarm"],
    correctAnswer: "Watch",
    partOfSpeech: "noun",
    ipa: "/wɒtʃ/",
    explanation: "Một thiết bị đeo trên cổ tay để xem thời gian.",
    example: "He looked at his watch to check the time.",
  },
  {
    image: "https://images.unsplash.com/photo-1585336261022-680e2954a78b?w=800",
    options: ["Chair", "Table", "Sofa", "Bed"],
    correctAnswer: "Chair",
    partOfSpeech: "noun",
    ipa: "/tʃeər/",
    explanation: "Một món đồ nội thất có một chỗ ngồi, có lưng và bốn chân.",
    example: "Please have a seat on this chair.",
  },
  {
    image: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=800",
    options: ["Phone", "Tablet", "Laptop", "Desktop"],
    correctAnswer: "Laptop",
    partOfSpeech: "noun",
    ipa: "/ˈlæp.tɒp/",
    explanation: "Một máy tính xách tay có thể mang đi.",
    example: "She does most of her work on her laptop.",
  },
  {
    image: "https://images.unsplash.com/photo-1515965655322-26f56156b245?w=800",
    options: ["Key", "Lock", "Door", "Window"],
    correctAnswer: "Key",
    partOfSpeech: "noun",
    ipa: "/kiː/",
    explanation: "Một miếng kim loại nhỏ dùng để mở hoặc khóa ổ khóa.",
    example: "I can't find the key to the front door.",
  },
  {
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800",
    options: ["Camera", "Lens", "Flash", "Tripod"],
    correctAnswer: "Camera",
    partOfSpeech: "noun",
    ipa: "/ˈkæm.rə/",
    explanation: "Một thiết bị dùng để chụp ảnh hoặc quay phim.",
    example: "He bought a new camera to take pictures on his trip.",
  },
  {
    image: "https://images.unsplash.com/photo-1575024357670-2b5164f47061?w=800",
    options: ["Guitar", "Piano", "Violin", "Drum"],
    correctAnswer: "Guitar",
    partOfSpeech: "noun",
    ipa: "/ɡɪˈtɑːr/",
    explanation:
      "Một nhạc cụ có dây, thường có sáu dây, được chơi bằng cách gảy.",
    example: "He plays the guitar in a band.",
  },
  {
    image: "https://images.unsplash.com/photo-1583787035686-91b82ad5d810?w=800",
    options: ["Cup", "Mug", "Glass", "Bottle"],
    correctAnswer: "Mug",
    partOfSpeech: "noun",
    ipa: "/mʌɡ/",
    explanation: "Một loại cốc lớn, có quai, thường dùng để uống đồ nóng.",
    example: "She enjoys a hot mug of coffee in the morning.",
  },
  {
    image: "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800",
    options: ["Sneakers", "Heels", "Flats", "Boots"],
    correctAnswer: "Sneakers",
    partOfSpeech: "noun",
    ipa: "/ˈsniː.kəz/",
    explanation: "Giày thể thao mềm, thoải mái.",
    example: "He wore his new sneakers to the gym.",
  },
  {
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800",
    options: ["Glasses", "Sunglasses", "Goggles", "Monocle"],
    correctAnswer: "Glasses",
    partOfSpeech: "noun",
    ipa: "/ˈɡlɑː.sɪz/",
    explanation:
      "Hai tròng kính được giữ trong một gọng để đeo trước mắt, giúp cải thiện thị lực.",
    example: "He needs glasses to read.",
  },
  {
    image: "https://images.unsplash.com/photo-1620288627223-162123523226?w=800",
    options: ["Pen", "Pencil", "Marker", "Crayon"],
    correctAnswer: "Pen",
    partOfSpeech: "noun",
    ipa: "/pen/",
    explanation: "Một dụng cụ có mực dùng để viết hoặc vẽ.",
    example: "Please sign the document with a black pen.",
  },
  {
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800",
    options: ["Running Shoe", "Sandal", "Boot", "Loafer"],
    correctAnswer: "Running Shoe",
    partOfSpeech: "noun",
    ipa: "/ˈrʌn.ɪŋ ʃuː/",
    explanation: "Một loại giày được thiết kế đặc biệt cho việc chạy bộ.",
    example: "He bought new running shoes for the marathon.",
  },
  {
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800",
    options: ["Couch", "Armchair", "Bench", "Stool"],
    correctAnswer: "Couch",
    partOfSpeech: "noun",
    ipa: "/kaʊtʃ/",
    explanation: "Một chiếc ghế dài, có đệm cho nhiều người ngồi.",
    example: "The family gathered on the couch to watch a movie.",
  },
  {
    image: "https://images.unsplash.com/photo-1546484475-7f7b5f6ce1d5?w=800",
    options: ["Backpack", "Handbag", "Suitcase", "Wallet"],
    correctAnswer: "Backpack",
    partOfSpeech: "noun",
    ipa: "/ˈbæk.pæk/",
    explanation: "Một chiếc túi được đeo trên lưng.",
    example: "He carries his books in a backpack.",
  },
  {
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800",
    options: ["Headphones", "Earbuds", "Speaker", "Microphone"],
    correctAnswer: "Headphones",
    partOfSpeech: "noun",
    ipa: "/ˈhed.fəʊnz/",
    explanation:
      "Một thiết bị có hai tai nghe được nối bằng một vòng qua đầu, dùng để nghe âm thanh.",
    example: "She listened to music with her headphones on the bus.",
  },
  {
    image: "https://images.unsplash.com/photo-1627483262268-9c2b5b2834b5?w=800",
    options: ["Keyboard", "Mouse", "Monitor", "Printer"],
    correctAnswer: "Keyboard",
    partOfSpeech: "noun",
    ipa: "/ˈkiː.bɔːd/",
    explanation: "Một bảng có các phím để nhập dữ liệu vào máy tính.",
    example: "My keyboard is not working properly.",
  },
  {
    image: "https://images.unsplash.com/photo-1519734007358-e33157b43566?w=800",
    options: ["Bicycle", "Scooter", "Skateboard", "Rollerblade"],
    correctAnswer: "Bicycle",
    partOfSpeech: "noun",
    ipa: "/ˈbaɪ.sɪ.kəl/",
    explanation: "Một phương tiện hai bánh di chuyển bằng cách đạp bàn đạp.",
    example: "He rides his bicycle to work every day.",
  },
  {
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800",
    options: ["Bed", "Pillow", "Blanket", "Mattress"],
    correctAnswer: "Bed",
    partOfSpeech: "noun",
    ipa: "/bed/",
    explanation: "Một món đồ nội thất dùng để ngủ hoặc nghỉ ngơi.",
    example: "It's time to go to bed.",
  },
  {
    image: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800",
    options: ["Bottle", "Can", "Jar", "Box"],
    correctAnswer: "Bottle",
    partOfSpeech: "noun",
    ipa: "/ˈbɒt.əl/",
    explanation:
      "Một vật chứa, thường làm bằng thủy tinh hoặc nhựa, dùng để đựng chất lỏng.",
    example: "He drank a whole bottle of water after the run.",
  },
  {
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800",
    options: ["Code", "Text", "Image", "Video"],
    correctAnswer: "Code",
    partOfSpeech: "noun",
    ipa: "/kəʊd/",
    explanation: "Các chỉ dẫn cho máy tính, được viết bằng ngôn ngữ lập trình.",
    example: "A programmer writes code to create software.",
  },

  // Thực phẩm & Đồ uống
  {
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800",
    options: ["Juice", "Milk", "Water", "Soda"],
    correctAnswer: "Juice",
    partOfSpeech: "noun",
    ipa: "/dʒuːs/",
    explanation: "Nước ép từ trái cây hoặc rau củ.",
    example: "I would like a glass of orange juice.",
  },
  {
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    options: ["Soup", "Salad", "Sandwich", "Stew"],
    correctAnswer: "Salad",
    partOfSpeech: "noun",
    ipa: "/ˈsæl.əd/",
    explanation:
      "Một món ăn gồm các loại rau sống trộn lẫn, thường có nước sốt.",
    example: "A green salad is a healthy lunch option.",
  },
  {
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
    options: ["Fries", "Burger", "Hotdog", "Taco"],
    correctAnswer: "Burger",
    partOfSpeech: "noun",
    ipa: "/ˈbɜː.ɡər/",
    explanation: "Một loại bánh sandwich gồm thịt băm kẹp trong bánh mì tròn.",
    example: "He ordered a classic beef burger with cheese.",
  },
  {
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    options: ["Meal", "Dish", "Plate", "Cuisine"],
    correctAnswer: "Meal",
    partOfSpeech: "noun",
    ipa: "/miːl/",
    explanation: "Một dịp ăn uống, hoặc thức ăn được ăn vào dịp đó.",
    example: "Breakfast is the first meal of the day.",
  },
  {
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800",
    options: ["Pepperoni", "Mushroom", "Olive", "Cheese Pizza"],
    correctAnswer: "Cheese Pizza",
    partOfSpeech: "noun",
    ipa: "/tʃiːz ˈpiːt.sə/",
    explanation: "Pizza chỉ có sốt cà chua và phô mai.",
    example: "My kids only like to eat plain cheese pizza.",
  },
  {
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800",
    options: ["Grilled Chicken", "Fried Fish", "Steak", "Pork Chop"],
    correctAnswer: "Grilled Chicken",
    partOfSpeech: "noun",
    ipa: "/ˌɡrɪld ˈtʃɪk.ɪn/",
    explanation: "Thịt gà được nấu bằng cách đặt trên vỉ nướng.",
    example: "Grilled chicken is a healthier option than fried chicken.",
  },
  {
    image: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800",
    options: ["Ice Cream", "Cake", "Cookie", "Donut"],
    correctAnswer: "Ice Cream",
    partOfSpeech: "noun",
    ipa: "/ˌaɪs ˈkriːm/",
    explanation: "Một món tráng miệng đông lạnh làm từ sữa hoặc kem.",
    example: "What's your favorite flavor of ice cream?",
  },
  {
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800",
    options: ["Cheeseburger", "Hamburger", "Veggie Burger", "Fish Burger"],
    correctAnswer: "Cheeseburger",
    partOfSpeech: "noun",
    ipa: "/ˈtʃiːzˌbɜː.ɡər/",
    explanation: "Một chiếc burger có thêm một lát phô mai.",
    example: "I'll have a cheeseburger with extra pickles.",
  },
  {
    image: "https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=800",
    options: ["Coffee", "Tea", "Hot Chocolate", "Latte"],
    correctAnswer: "Coffee",
    partOfSpeech: "noun",
    ipa: "/ˈkɒf.i/",
    explanation:
      "Một loại đồ uống nóng, màu nâu sẫm, được làm từ hạt cà phê rang.",
    example: "I need a cup of coffee to wake up in the morning.",
  },
  {
    image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800",
    options: ["Ingredients", "Spices", "Herbs", "Seasoning"],
    correctAnswer: "Ingredients",
    partOfSpeech: "noun",
    ipa: "/ɪnˈɡriː.di.ənts/",
    explanation: "Các thành phần thực phẩm được dùng để nấu một món ăn.",
    example: "Please list all the ingredients for this recipe.",
  },

  // Địa điểm & Tòa nhà
  {
    image: "https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=800",
    options: ["House", "Apartment", "Castle", "Mansion"],
    correctAnswer: "House",
    partOfSpeech: "noun",
    ipa: "/haʊs/",
    explanation: "Một tòa nhà dành cho một gia đình ở.",
    example: "They live in a small house in the suburbs.",
  },
  {
    image: "https://images.unsplash.com/photo-1562790331-90cb931e8ee2?w=800",
    options: ["School", "University", "Library", "College"],
    correctAnswer: "School",
    partOfSpeech: "noun",
    ipa: "/skuːl/",
    explanation: "Nơi trẻ em đến để được giáo dục.",
    example: "The children go to school from Monday to Friday.",
  },
  {
    image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800",
    options: ["Shop", "Store", "Market", "Mall"],
    correctAnswer: "Shop",
    partOfSpeech: "noun",
    ipa: "/ʃɒp/",
    explanation: "Một nơi bán hàng hóa.",
    example: "I need to go to the shop to buy some milk.",
  },
  {
    image: "https://images.unsplash.com/photo-1587213824987-a240b6df7856?w=800",
    options: ["Hospital", "Clinic", "Pharmacy", "Doctor Office"],
    correctAnswer: "Hospital",
    partOfSpeech: "noun",
    ipa: "/ˈhɒs.pɪ.təl/",
    explanation:
      "Nơi chăm sóc và điều trị cho người bệnh hoặc người bị thương.",
    example: "He was taken to the hospital after the accident.",
  },
  {
    image: "https://images.unsplash.com/photo-1520106212299-d99c443e4568?w=800",
    options: ["Airport", "Train Station", "Bus Stop", "Harbor"],
    correctAnswer: "Airport",
    partOfSpeech: "noun",
    ipa: "/ˈeə.pɔːt/",
    explanation:
      "Nơi máy bay cất cánh và hạ cánh, có các tòa nhà để hành khách chờ.",
    example: "We need to be at the airport two hours before our flight.",
  },
  {
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    options: ["Restaurant", "Cafe", "Bar", "Diner"],
    correctAnswer: "Restaurant",
    partOfSpeech: "noun",
    ipa: "/ˈres.trɒnt/",
    explanation: "Nơi bạn có thể mua và ăn một bữa ăn.",
    example: "We went to an Italian restaurant for dinner.",
  },
  {
    image: "https://images.unsplash.com/photo-1531214159280-eff74342527b?w=800",
    options: ["Beach", "Coast", "Shore", "Seaside"],
    correctAnswer: "Beach",
    partOfSpeech: "noun",
    ipa: "/biːtʃ/",
    explanation: "Một khu vực có cát hoặc sỏi bên cạnh biển hoặc hồ.",
    example: "The children love playing on the beach.",
  },
  {
    image: "https://images.unsplash.com/photo-1533109721025-d1ae7ee7c1e1?w=800",
    options: ["Bridge", "Tunnel", "Overpass", "Viaduct"],
    correctAnswer: "Bridge",
    partOfSpeech: "noun",
    ipa: "/brɪdʒ/",
    explanation:
      "Một cấu trúc được xây dựng bắc qua sông, đường bộ hoặc đường sắt.",
    example: "The Golden Gate Bridge is a famous landmark.",
  },
  {
    image: "https://images.unsplash.com/photo-1569949381669-ecf31ae8e613?w=800",
    options: ["Farm", "Ranch", "Orchard", "Vineyard"],
    correctAnswer: "Farm",
    partOfSpeech: "noun",
    ipa: "/fɑːm/",
    explanation: "Một khu vực đất đai dùng để trồng trọt hoặc chăn nuôi.",
    example: "My grandparents live on a farm.",
  },
  {
    image: "https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=800",
    options: ["City", "Town", "Village", "Metropolis"],
    correctAnswer: "City",
    partOfSpeech: "noun",
    ipa: "/ˈsɪt.i/",
    explanation:
      "Một nơi lớn có nhiều nhà cửa, cửa hàng và người dân sinh sống.",
    example: "New York is a very busy city.",
  },

  // Khác
  {
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800",
    options: ["Money", "Coin", "Bill", "Cash"],
    correctAnswer: "Money",
    partOfSpeech: "noun",
    ipa: "/ˈmʌn.i/",
    explanation:
      "Thứ bạn dùng để mua hàng hóa và dịch vụ, thường là tiền xu hoặc tiền giấy.",
    example: "You need money to buy food and clothes.",
  },
  {
    image: "https://images.unsplash.com/photo-1530026405182-273c32de5878?w=800",
    options: ["Fire", "Flame", "Blaze", "Ember"],
    correctAnswer: "Fire",
    partOfSpeech: "noun",
    ipa: "/faɪər/",
    explanation: "Ánh sáng, nhiệt và khói được tạo ra khi có thứ gì đó cháy.",
    example: "The campers sat around the fire to keep warm.",
  },
  {
    image: "https://images.unsplash.com/photo-1495020689067-958852a7765e?w=800",
    options: ["Article", "Headline", "Paragraph", "Newspaper"],
    correctAnswer: "Newspaper",
    partOfSpeech: "noun",
    ipa: "/ˈnjuːzˌpeɪ.pər/",
    explanation:
      "Một tập hợp các tờ giấy lớn in tin tức, được bán hàng ngày hoặc hàng tuần.",
    example: "My father reads the newspaper every morning.",
  },
  {
    image: "https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=800",
    options: ["Writing", "Drawing", "Painting", "Sketching"],
    correctAnswer: "Writing",
    partOfSpeech: "noun",
    ipa: "/ˈraɪ.tɪŋ/",
    explanation: "Hoạt động viết chữ hoặc từ trên một bề mặt.",
    example: "Her writing is very neat and easy to read.",
  },
  {
    image: "https://images.unsplash.com/photo-1528642474498-1af0c17fd8c3?w=800",
    options: ["Map", "Globe", "Atlas", "Chart"],
    correctAnswer: "Map",
    partOfSpeech: "noun",
    ipa: "/mæp/",
    explanation:
      "Một bản vẽ của một khu vực cụ thể, chẳng hạn như một thành phố hoặc một quốc gia.",
    example: "We used a map to find our way back to the hotel.",
  },
  {
    image: "https://images.unsplash.com/photo-1581726707445-7523a451bdb4?w=800",
    options: ["Ball", "Sphere", "Globe", "Orb"],
    correctAnswer: "Ball",
    partOfSpeech: "noun",
    ipa: "/bɔːl/",
    explanation:
      "Một vật thể tròn dùng trong các trò chơi, chẳng hạn như bóng đá hoặc quần vợt.",
    example: "The boy kicked the ball into the goal.",
  },
  {
    image: "https://images.unsplash.com/photo-1511871893375-6838c73b7599?w=800",
    options: ["Music", "Song", "Melody", "Rhythm"],
    correctAnswer: "Music",
    partOfSpeech: "noun",
    ipa: "/ˈmjuː.zɪk/",
    explanation:
      "Một chuỗi các âm thanh được tạo ra bởi giọng hát hoặc nhạc cụ.",
    example: "Classical music helps me relax.",
  },
  {
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800",
    options: ["Team", "Group", "Crew", "Squad"],
    correctAnswer: "Team",
    partOfSpeech: "noun",
    ipa: "/tiːm/",
    explanation:
      "Một nhóm người làm việc cùng nhau hoặc chơi một môn thể thao cùng nhau.",
    example: "Our football team won the championship.",
  },
  {
    image: "https://images.unsplash.com/photo-1633409361618-c1674c52a0a2?w=800",
    options: ["Light", "Lamp", "Bulb", "Lantern"],
    correctAnswer: "Light",
    partOfSpeech: "noun",
    ipa: "/laɪt/",
    explanation:
      "Năng lượng từ mặt trời, đèn, v.v. cho phép chúng ta nhìn thấy mọi thứ.",
    example: "Please turn on the light; it's getting dark.",
  },
  {
    image: "https://images.unsplash.com/photo-1506953823073-a72c6b41240b?w=800",
    options: ["Road", "Highway", "Street", "Lane"],
    correctAnswer: "Road",
    partOfSpeech: "noun",
    ipa: "/rəʊd/",
    explanation: "Một bề mặt cứng mà xe cộ có thể đi lại.",
    example: "This road leads to the next town.",
  },
  {
    image: "https://images.unsplash.com/photo-1505682634904-d7c8d95cdc50?w=800",
    options: ["Desk", "Table", "Counter", "Bench"],
    correctAnswer: "Desk",
    partOfSpeech: "noun",
    ipa: "/desk/",
    explanation: "Một loại bàn thường có ngăn kéo, dùng để viết hoặc làm việc.",
    example: "She sat at her desk to finish her homework.",
  },
  {
    image: "https://images.unsplash.com/photo-1542435503-956c469947f6?w=800",
    options: ["Work", "Job", "Task", "Career"],
    correctAnswer: "Work",
    partOfSpeech: "noun",
    ipa: "/wɜːk/",
    explanation: "Hoạt động mà bạn làm để kiếm tiền.",
    example: "He starts work at 9 a.m. every day.",
  },
  {
    image: "https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=800",
    options: ["Office", "Studio", "Workspace", "Cubicle"],
    correctAnswer: "Office",
    partOfSpeech: "noun",
    ipa: "/ˈɒf.ɪs/",
    explanation:
      "Một căn phòng hoặc tòa nhà nơi mọi người làm công việc bàn giấy.",
    example: "My office is on the fifth floor.",
  },
  {
    image: "https://images.unsplash.com/photo-1524678606370-a47601cb12db?w=800",
    options: ["Concert", "Show", "Performance", "Gig"],
    correctAnswer: "Concert",
    partOfSpeech: "noun",
    ipa: "/ˈkɒn.sət/",
    explanation: "Một buổi trình diễn âm nhạc trước công chúng.",
    example: "We're going to a rock concert on Saturday.",
  },
  {
    image: "https://images.unsplash.com/photo-1543353123-535799a61358?w=800",
    options: ["Gift", "Present", "Box", "Surprise"],
    correctAnswer: "Gift",
    partOfSpeech: "noun",
    ipa: "/ɡɪft/",
    explanation:
      "Một món đồ được tặng cho ai đó mà không cần trả tiền, đặc biệt là trong một dịp đặc biệt.",
    example: "She received a beautiful gift for her birthday.",
  },
];

export default vocabularies;
